#!/usr/bin/env python3
"""Fit ECM schedule from GMP-ECM 7.0.5 table.

Uses piecewise log-linear interpolation between anchor points so that
B1/B2/curves match the GMP-ECM table exactly at digit boundaries and
interpolate smoothly in between.

Output: include/zfactor/eecm/schedule_generated.h
"""
import math
import numpy as np
from pathlib import Path

# GMP-ECM 7.0.5 optimal parameters (digits, B1, B2, expected_curves)
GMP_ECM_TABLE = [
    (20,  11_000,        1.9e6,         74),
    (25,  50_000,        1.3e7,        221),
    (30,  250_000,       1.3e8,        453),
    (35,  1_000_000,     1.0e9,        984),
    (40,  3_000_000,     5.7e9,       2541),
    (45,  11_000_000,    3.5e10,      4949),
    (50,  43_000_000,    2.4e11,      8266),
    (55,  110_000_000,   7.8e11,     20158),
    (60,  260_000_000,   3.2e12,     47173),
    (65,  850_000_000,   1.6e13,     77666),
]

LOG2_10 = math.log2(10)  # ~3.3219

def interp_log(bits_query, bits_arr, vals_arr):
    """Piecewise log-linear interpolation. Clamps at edges."""
    if bits_query <= bits_arr[0]:
        return vals_arr[0]
    if bits_query >= bits_arr[-1]:
        # Extrapolate from last segment
        i = len(bits_arr) - 2
        t = (bits_query - bits_arr[i]) / (bits_arr[i+1] - bits_arr[i])
        return math.exp(math.log(vals_arr[i]) * (1-t) + math.log(vals_arr[i+1]) * t)
    # Find segment
    for i in range(len(bits_arr) - 1):
        if bits_arr[i] <= bits_query <= bits_arr[i+1]:
            t = (bits_query - bits_arr[i]) / (bits_arr[i+1] - bits_arr[i])
            return math.exp(math.log(vals_arr[i]) * (1-t) + math.log(vals_arr[i+1]) * t)
    return vals_arr[-1]

def round_to_significant(x, sig):
    if x == 0: return 0
    d = math.ceil(math.log10(abs(x)))
    power = sig - int(d)
    factor = 10 ** power
    return int(round(x * factor) / factor)

def main():
    digits = [row[0] for row in GMP_ECM_TABLE]
    B1     = [row[1] for row in GMP_ECM_TABLE]
    B2     = [row[2] for row in GMP_ECM_TABLE]
    curves = [row[3] for row in GMP_ECM_TABLE]

    bits_anchor = [d * LOG2_10 for d in digits]

    # Verify fit at anchor points
    print("# Verification at anchor points:")
    print(f"# {'digits':>6} {'bits':>6} {'B1_table':>12} {'B1_fit':>12} {'B2_table':>14} {'B2_fit':>14} {'cv_table':>8} {'cv_fit':>8}")
    for i, d in enumerate(digits):
        b = d * LOG2_10
        b1_f = interp_log(b, bits_anchor, B1)
        b2_f = interp_log(b, bits_anchor, B2)
        cv_f = interp_log(b, bits_anchor, curves)
        print(f"# {d:6d} {b:6.1f} {B1[i]:12.0f} {b1_f:12.0f} {B2[i]:14.0f} {b2_f:14.0f} {curves[i]:8.0f} {cv_f:8.0f}")

    # Evaluate at every 2 bits from 20..160
    rows = []
    print()
    print(f"# {'bits':>4} {'B1':>12} {'B2':>14} {'curves':>8}")
    for b in range(20, 162, 2):
        b1 = interp_log(b, bits_anchor, B1)
        b2 = interp_log(b, bits_anchor, B2)
        cv = interp_log(b, bits_anchor, curves)
        b1_r = round_to_significant(b1, 3)
        b2_r = round_to_significant(b2, 3)
        cv_r = max(1, round(cv))
        rows.append((b, b1_r, b2_r, cv_r))
        print(f"# {b:4d} {b1_r:12d} {b2_r:14d} {cv_r:8d}")

    # Emit C++ header
    out = Path("include/zfactor/eecm/schedule_generated.h")
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w") as f:
        f.write("// Generated by tools/eecm/fit_schedule.py — do not edit.\n")
        f.write("// Piecewise log-linear interpolation of GMP-ECM 7.0.5 table\n")
        f.write("// (B1, B2, expected_curves) at 5-digit increments,\n")
        f.write("// evaluated at every 2 bits from 20..160.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace zfactor::eecm {\n\n")
        f.write("struct schedule_row {\n")
        f.write("    uint8_t  bits;        // target factor bit length (lower bound)\n")
        f.write("    uint64_t B1;          // stage-1 bound\n")
        f.write("    uint64_t B2;          // stage-2 bound\n")
        f.write("    uint32_t avg_curves;  // expected curves to find one factor\n")
        f.write("};\n\n")
        f.write(f"constexpr schedule_row schedule[] = {{\n")
        for b, b1, b2, cv in rows:
            f.write(f"    {{ {b:3d}, {b1:>14d}ULL, {b2:>15d}ULL, {cv:>10d}u }},\n")
        f.write("};\n\n")
        f.write(f"constexpr int schedule_size = {len(rows)};\n\n")
        f.write("// Look up the schedule row whose `bits` is the largest entry <= target.\n")
        f.write("// (For target < 20 we return the first row.)\n")
        f.write("inline const schedule_row& schedule_for_bits(int target) {\n")
        f.write("    if (target <= schedule[0].bits) return schedule[0];\n")
        f.write("    for (int i = schedule_size - 1; i >= 0; --i)\n")
        f.write("        if (schedule[i].bits <= target) return schedule[i];\n")
        f.write("    return schedule[0];\n")
        f.write("}\n\n")
        f.write("}  // namespace zfactor::eecm\n")
    print(f"\nWrote {out}")

if __name__ == "__main__":
    main()
