// Generated by tools/eecm/optimize_schedule.py — do not edit.
// 2D Nelder-Mead optimization of E[cost] = (T_s1 + T_s2) / P(B1,B2,p).
// Probability: Dickman rho, extra smoothness exp(3.134), empirical 2.2× boost.
// Cost model fitted from calibration data (N=4).
#pragma once

#include <cstdint>

namespace zfactor::ecm {

struct ScheduleRow {
    uint8_t  bits;        // target factor bit length
    uint64_t B1;          // stage-1 bound
    uint64_t B2;          // stage-2 bound
    uint32_t avg_curves;  // expected curves to find one factor
};

constexpr ScheduleRow schedule[] = {
    {  20,              25ULL,              945ULL,          1u },
    {  25,              61ULL,             2190ULL,          2u },
    {  30,             141ULL,             4937ULL,          3u },
    {  35,             290ULL,             9893ULL,          5u },
    {  40,             570ULL,            18997ULL,          8u },
    {  45,            1092ULL,            35726ULL,         12u },
    {  50,            2021ULL,            65223ULL,         18u },
    {  55,            3598ULL,           114588ULL,         26u },
    {  60,            6184ULL,           194242ULL,         37u },
    {  65,           10464ULL,           324876ULL,         53u },
    {  70,           17490ULL,           537555ULL,         74u },
    {  75,           28829ULL,           878141ULL,        101u },
    {  80,           82581ULL,          6137745ULL,         64u },
    {  85,          132548ULL,         12277109ULL,         81u },
    {  90,          210059ULL,         24271702ULL,        103u },
    {  95,          328359ULL,         47314084ULL,        130u },
    { 100,          506063ULL,         90790495ULL,        165u },
    { 105,          769898ULL,        171651113ULL,        209u },
    { 110,         1158583ULL,        320585384ULL,        264u },
    { 115,         1728771ULL,        593532366ULL,        332u },
    { 120,         2562958ULL,       1092655715ULL,        415u },
    { 125,         3777370ULL,       2001449663ULL,        518u },
    { 130,         5532033ULL,       3643832181ULL,        643u },
    { 135,         8047782ULL,       6587541877ULL,        797u },
    { 140,        11627305ULL,      11818197064ULL,        985u },
    { 145,        16683867ULL,      21033133165ULL,       1216u },
    { 150,        23783698ULL,      37144341410ULL,       1500u },
    { 155,        33692307ULL,      65100777674ULL,       1848u },
    { 160,        47469753ULL,     113363934907ULL,       2271u },
    { 165,        66546342ULL,     196267914788ULL,       2787u },
    { 170,        92890911ULL,     338179681214ULL,       3412u },
    { 175,       129134649ULL,     580061445456ULL,       4167u },
    { 180,       178838311ULL,     990814315813ULL,       5079u },
    { 185,       246756257ULL,    1685417830171ULL,       6176u },
    { 190,       339168241ULL,    2854199453454ULL,       7497u },
    { 195,       464378639ULL,    4810602939745ULL,       9088u },
    { 200,       633357988ULL,    8069155843400ULL,      11001u },
};

constexpr int schedule_size = 37;

// Look up the schedule row whose `bits` is the largest entry <= target.
inline const ScheduleRow& schedule_for_bits(int target) {
    if (target <= schedule[0].bits) return schedule[0];
    for (int i = schedule_size - 1; i >= 0; --i)
        if (schedule[i].bits <= target) return schedule[i];
    return schedule[0];
}

}  // namespace zfactor::ecm
