#pragma once

// Generated by scripts/gen_mpn.py. Do not edit by hand.

#define ZFACTOR_MPN_DECLARE_ONLY 1
#include "mpn_generic.h"
#undef ZFACTOR_MPN_DECLARE_ONLY

namespace zfactor::mpn {

template<int B>
__attribute__((always_inline)) inline limb_t add_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_add_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline limb_t add_block(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    return generic_add_block<B>(r, a, b, cy);
}

template<int B>
__attribute__((always_inline)) inline limb_t sub_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_sub_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline limb_t sub_block(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    return generic_sub_block<B>(r, a, b, bw);
}

template<int B>
__attribute__((always_inline)) inline limb_t addmul1_block(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
    return generic_addmul1_block<B>(r, a, scalar, cy);
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<1>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<1>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<2>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<2>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<3>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<3>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<4>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<4>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<5>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<5>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<6>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<6>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<7>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<7>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}


template<>
__attribute__((always_inline)) inline limb_t add_block_first<8>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t cy, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "adcq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t add_block<8>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "adcq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block_first<1>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<1>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<2>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<2>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<3>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<3>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<4>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<4>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<5>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<5>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<6>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<6>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<7>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<7>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}


template<>
__attribute__((always_inline)) inline limb_t sub_block_first<8>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t bw, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "sbbq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t sub_block<8>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "sbbq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<1>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adcq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;

#else
    return generic_addmul1_block<1>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<2>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adcq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t1]\n\t"
            "addq %[co], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t1;

#else
    return generic_addmul1_block<2>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<3>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[co]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adcq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t1]\n\t"
            "addq %[co], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 16(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t2;

#else
    return generic_addmul1_block<3>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<4>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;

        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adcq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t1]\n\t"
            "addq %[co], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 16(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 24(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t1;

#else
    return generic_addmul1_block<4>(r, a, scalar, cy);
#endif
}

template<int N>
__attribute__((always_inline)) inline limb_t add(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= 8) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t cy = 0;
        if constexpr (full != 0) {
            cy = add_block_first<8>(r, a, b);
            for (int j = 1; j < full; ++j)
                cy = add_block<8>(r + j * 8, a + j * 8, b + j * 8, cy);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                cy = add_block_first<rem>(r, a, b);
            else
                cy = add_block<rem>(r + full * 8, a + full * 8, b + full * 8, cy);
        }
        return cy;
    } else if constexpr (N <= 16) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t cy = add_block_first<8>(r, a, b);
        for (int j = 1; j < full; ++j)
            cy = add_block<8>(r + j * 8, a + j * 8, b + j * 8, cy);
        if constexpr (rem != 0)
            cy = add_block<rem>(r + full * 8, a + full * 8, b + full * 8, cy);
        return cy;
    } else {
        return generic_add<N>(r, a, b);
    }
}

template<int N>
__attribute__((always_inline)) inline limb_t sub(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= 8) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t bw = 0;
        if constexpr (full != 0) {
            bw = sub_block_first<8>(r, a, b);
            for (int j = 1; j < full; ++j)
                bw = sub_block<8>(r + j * 8, a + j * 8, b + j * 8, bw);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                bw = sub_block_first<rem>(r, a, b);
            else
                bw = sub_block<rem>(r + full * 8, a + full * 8, b + full * 8, bw);
        }
        return bw;
    } else if constexpr (N <= 16) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t bw = sub_block_first<8>(r, a, b);
        for (int j = 1; j < full; ++j)
            bw = sub_block<8>(r + j * 8, a + j * 8, b + j * 8, bw);
        if constexpr (rem != 0)
            bw = sub_block<rem>(r + full * 8, a + full * 8, b + full * 8, bw);
        return bw;
    } else {
        return generic_sub<N>(r, a, b);
    }
}

template<int N>
__attribute__((always_inline)) inline limb_t addmul1(limb_t* r, const limb_t* a, limb_t b) {
    if constexpr (N <= 4) {
        constexpr int full = N / 4;
        constexpr int rem = N % 4;
        limb_t cy = 0;
        if constexpr (full != 0) {
            cy = addmul1_block<4>(r, a, b, cy);
            for (int j = 1; j < full; ++j)
                cy = addmul1_block<4>(r + j * 4, a + j * 4, b, cy);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                cy = addmul1_block<rem>(r, a, b, cy);
            else
                cy = addmul1_block<rem>(r + full * 4, a + full * 4, b, cy);
        }
        return cy;
    } else if constexpr (N <= 16) {
        constexpr int full = N / 4;
        constexpr int rem = N % 4;
        limb_t cy = addmul1_block<4>(r, a, b, 0);
        for (int j = 1; j < full; ++j)
            cy = addmul1_block<4>(r + j * 4, a + j * 4, b, cy);
        if constexpr (rem != 0)
            cy = addmul1_block<rem>(r + full * 4, a + full * 4, b, cy);
        return cy;
    } else {
        return generic_addmul1<N>(r, a, b);
    }
}

} // namespace zfactor::mpn

#include "mpn_common.h"
