// Generated by tools/fixint/gen_divexact1.py — do not edit.
// Included inside namespace zfactor::fixint, guarded by __BMI2__.

// N=3 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_3(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=3 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_3(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=4 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_4(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=4 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_4(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=5 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_5(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=5 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_5(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=6 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_6(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=6 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_6(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=7 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_7(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 6 ---
        "movq 48(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 48(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=7 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_7(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 6 ---
        "movq 48(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 48(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=8 in-place divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_ip_8(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 6 ---
        "movq 48(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 48(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 7 ---
        "movq 56(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 56(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

// N=8 divexact1 — generated by gen_divexact1.py
__attribute__((always_inline))
inline uint64_t divexact1_8(uint64_t* dst,
                        const uint64_t* src,
                        uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // --- limb 0 ---
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q], %[s]\n\t"
        "movq %[q], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"
        // --- limb 1 ---
        "movq 8(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 2 ---
        "movq 16(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 16(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 3 ---
        "movq 24(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 24(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 4 ---
        "movq 32(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 32(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 5 ---
        "movq 40(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 40(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 6 ---
        "movq 48(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 48(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        // --- limb 7 ---
        "movq 56(%[src]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 56(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"
        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}
