#pragma once

// Out-of-place divexact by a single u64 limb: dst[] = src[] / d, exact.
// Returns nonzero borrow if the division was NOT exact (src not divisible by d).
// Caller must precompute inv = d^{-1} mod 2^64 via Hensel lifting.
//
// N=1: pure C++ (__int128).
// N=2: hand-written inline asm (mulx + sub + sbb).
// N=3-8: generated by tools/fixint/gen_divexact1.py.

#include <cstdint>
#include "../mpn.h"

namespace zfactor::fixint {

// Compute d^{-1} mod 2^64 via Hensel lifting (6 Newton iterations).
// d must be odd.
inline uint64_t inverse_mod_2_64(uint64_t d) {
    uint64_t inv = d;  // d * d ≡ d^2 ≡ 1 (mod 2) for odd d, but start with d itself
    // Newton: inv = inv * (2 - d * inv), doubling correct bits each step.
    // Starting from inv = d: d*d = d^2 ≡ 1 (mod 2), so 1 bit correct.
    // Actually, standard start: inv = 1, then iterate.
    inv = 1;
    for (int i = 0; i < 6; i++)
        inv *= 2 - d * inv;
    return inv;
}

// ============================================================================
// N = 1: C++ with __int128
// ============================================================================

__attribute__((always_inline))
inline uint64_t divexact1_1(uint64_t* dst,
                            const uint64_t* src,
                            uint64_t inv, uint64_t d) {
    uint64_t q = src[0] * inv;
    dst[0] = q;
    // borrow = hi(q * d): if exact, q*d == src[0] so hi == 0
    return (uint64_t)(((unsigned __int128)q * d) >> 64);
}

// ============================================================================
// N = 2: hand-written inline asm
// ============================================================================
//
// Algorithm per limb i:
//   s = src[i] - borrow
//   q = s * inv          (lo of mulx)
//   dst[i] = q
//   borrow = hi(q * d)   (hi of mulx) + borrow_from_sub
//
// We keep d in rdx for mulx. inv is in a register.
// The two mulx per limb: one for s*inv (need lo=q), one for q*d (need hi=borrow).
// But mulx always uses rdx. So we:
//   1. Put inv in rdx, mulx s → (hi_unused, q)
//   2. Swap: put d in rdx, mulx q → (new_borrow, lo_unused)
// Cost: 2 mulx + 1 sub + 1 sbb + 1 mov(rdx) per limb.

#if defined(__BMI2__)

__attribute__((always_inline))
inline uint64_t divexact1_2(uint64_t* dst,
                            const uint64_t* src,
                            uint64_t inv, uint64_t d) {
    uint64_t borrow, q0, q1, tmp;
    asm volatile(
        // Limb 0: s = src[0], q = s * inv, borrow = hi(q * d)
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[src]), %[q0], %[tmp]\n\t"       // (tmp, q0) = src[0] * inv
        "movq %[q0], (%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q0], %[tmp], %[borrow]\n\t"      // (borrow, tmp) = q0 * d

        // Limb 1: s = src[1] - borrow, q = s * inv, borrow = hi(q * d) + sub_borrow
        "movq 8(%[src]), %[tmp]\n\t"
        "subq %[borrow], %[tmp]\n\t"               // s = src[1] - borrow, CF = sub borrow
        "sbbq %[q0], %[q0]\n\t"                    // q0 = -CF (reuse q0 as sub_borrow; 0 or -1)
        "negq %[q0]\n\t"                            // q0 = 0 or 1
        "movq %[inv], %%rdx\n\t"
        "mulxq %[tmp], %[q1], %[tmp]\n\t"          // (tmp, q1) = s * inv
        "movq %[q1], 8(%[dst])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q1], %[tmp], %[borrow]\n\t"       // (borrow, tmp) = q1 * d
        "addq %[q0], %[borrow]\n\t"                // borrow = hi(q*d) + sub_borrow

        : [borrow] "=&r"(borrow), [q0] "=&r"(q0), [q1] "=&r"(q1), [tmp] "=&r"(tmp)
        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

#else

// Fallback: C++ for non-BMI2
__attribute__((always_inline))
inline uint64_t divexact1_2(uint64_t* dst,
                            const uint64_t* src,
                            uint64_t inv, uint64_t d) {
    uint64_t borrow = 0;
    for (int i = 0; i < 2; i++) {
        uint64_t s = src[i] - borrow;
        borrow = (src[i] < borrow);
        uint64_t q = s * inv;
        dst[i] = q;
        borrow += (uint64_t)(((unsigned __int128)q * d) >> 64);
    }
    return borrow;
}

#endif // __BMI2__

// ============================================================================
// N >= 3: generated asm (included from divexact1_generated.h)
// Fallback: generic C++ loop
// ============================================================================

// Generic C++ fallback for any N (also used when generated asm not available)
template<int N>
__attribute__((always_inline))
inline uint64_t divexact1_generic(uint64_t* dst,
                                  const uint64_t* src,
                                  uint64_t inv, uint64_t d) {
    uint64_t borrow = 0;
    for (int i = 0; i < N; i++) {
        uint64_t s = src[i] - borrow;
        borrow = (src[i] < borrow);
        uint64_t q = s * inv;
        dst[i] = q;
        borrow += (uint64_t)(((unsigned __int128)q * d) >> 64);
    }
    return borrow;
}

#if defined(__BMI2__) && __has_include("divexact1_generated.h")
#include "divexact1_generated.h"
#endif

// Dispatch helper: picks generated asm when available, else generic.
namespace detail_divexact {

template<int N>
__attribute__((always_inline))
inline uint64_t dispatch(uint64_t* dst,
                         const uint64_t* src,
                         uint64_t inv, uint64_t d) {
    return divexact1_generic<N>(dst, src, inv, d);
}

#if defined(__BMI2__) && __has_include("divexact1_generated.h")
#define ZFACTOR_DIVEXACT1_SPEC(NN)                                           \
    template<> __attribute__((always_inline))                                  \
    inline uint64_t dispatch<NN>(uint64_t* dst,                 \
                                 const uint64_t* src,           \
                                 uint64_t inv, uint64_t d) {                 \
        return divexact1_##NN(dst, src, inv, d);                             \
    }
ZFACTOR_DIVEXACT1_SPEC(3)
ZFACTOR_DIVEXACT1_SPEC(4)
ZFACTOR_DIVEXACT1_SPEC(5)
ZFACTOR_DIVEXACT1_SPEC(6)
ZFACTOR_DIVEXACT1_SPEC(7)
ZFACTOR_DIVEXACT1_SPEC(8)
#undef ZFACTOR_DIVEXACT1_SPEC
#endif

} // namespace detail_divexact

template<int N>
__attribute__((always_inline))
inline uint64_t divexact1(uint64_t* dst,
                          const uint64_t* src,
                          uint64_t inv, uint64_t d) {
    if constexpr (N == 1) return divexact1_1(dst, src, inv, d);
    else if constexpr (N == 2) return divexact1_2(dst, src, inv, d);
    else return detail_divexact::dispatch<N>(dst, src, inv, d);
}

// ============================================================================
// In-place variants: n /= d, returns borrow (0 if exact).
// Single pointer, one fewer register, no aliasing confusion.
// ============================================================================

// N=1: C++
__attribute__((always_inline))
inline uint64_t divexact1_ip_1(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t q = n[0] * inv;
    n[0] = q;
    return (uint64_t)(((unsigned __int128)q * d) >> 64);
}

#if defined(__BMI2__)

// N=2: hand-written in-place asm. One pointer [n], reads then writes each limb.
__attribute__((always_inline))
inline uint64_t divexact1_ip_2(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow, q, s;
    asm volatile(
        // Limb 0: q = n[0] * inv, n[0] = q, borrow = hi(q * d)
        "movq %[inv], %%rdx\n\t"
        "mulxq (%[n]), %[q], %[s]\n\t"
        "movq %[q], (%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[q], %[s], %[borrow]\n\t"

        // Limb 1: s = n[1] - borrow, q = s * inv, n[1] = q, borrow = hi(q*d) + sub_borrow
        "movq 8(%[n]), %[s]\n\t"
        "subq %[borrow], %[s]\n\t"
        "sbbq %[q], %[q]\n\t"
        "negq %[q]\n\t"
        "movq %[inv], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "movq %[s], 8(%[n])\n\t"
        "movq %[d], %%rdx\n\t"
        "mulxq %[s], %[s], %[borrow]\n\t"
        "addq %[q], %[borrow]\n\t"

        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)
        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)
        : "rdx", "cc", "memory"
    );
    return borrow;
}

#endif // __BMI2__

// Generic in-place fallback
template<int N>
__attribute__((always_inline))
inline uint64_t divexact1_ip_generic(uint64_t* n, uint64_t inv, uint64_t d) {
    uint64_t borrow = 0;
    for (int i = 0; i < N; i++) {
        uint64_t orig = n[i];
        uint64_t s = orig - borrow;
        borrow = (orig < borrow);
        uint64_t q = s * inv;
        n[i] = q;
        borrow += (uint64_t)(((unsigned __int128)q * d) >> 64);
    }
    return borrow;
}

// ============================================================================
// LLVM IR-generated peel loops (src/fixint/divexact_x86_64.S)
// ============================================================================
// These are complete peel loops: they divide n in-place repeatedly until
// the division is inexact, saving a copy to tmp after each success.
// On failure, n is restored from tmp. Returns the peel count.
//
// Signature: i32 peel_N(ptr n, i64 inv, i64 d, ptr tmp)
// Calling convention: System V AMD64 (rdi=n, rsi=inv, rdx=d, rcx=tmp)

#if defined(__x86_64__) && defined(ZFACTOR_HAS_BMI2)
extern "C" {
uint32_t divexact1_ip_peel_2(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_3(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_4(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_5(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_6(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_7(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
uint32_t divexact1_ip_peel_8(uint64_t* n, uint64_t inv, uint64_t d, uint64_t* tmp);
}
#endif

// In-place dispatch
namespace detail_divexact_ip {

template<int N>
__attribute__((always_inline))
inline uint64_t dispatch(uint64_t* n, uint64_t inv, uint64_t d) {
    return divexact1_ip_generic<N>(n, inv, d);
}

#if defined(__BMI2__) && __has_include("divexact1_generated.h")
#define ZFACTOR_DIVEXACT1_IP_SPEC(NN)                                        \
    template<> __attribute__((always_inline))                                  \
    inline uint64_t dispatch<NN>(uint64_t* n, uint64_t inv, uint64_t d) {    \
        return divexact1_ip_##NN(n, inv, d);                                 \
    }
ZFACTOR_DIVEXACT1_IP_SPEC(3)
ZFACTOR_DIVEXACT1_IP_SPEC(4)
ZFACTOR_DIVEXACT1_IP_SPEC(5)
ZFACTOR_DIVEXACT1_IP_SPEC(6)
ZFACTOR_DIVEXACT1_IP_SPEC(7)
ZFACTOR_DIVEXACT1_IP_SPEC(8)
#undef ZFACTOR_DIVEXACT1_IP_SPEC
#endif

} // namespace detail_divexact_ip

template<int N>
__attribute__((always_inline))
inline uint64_t divexact1_ip(uint64_t* n, uint64_t inv, uint64_t d) {
    if constexpr (N == 1) return divexact1_ip_1(n, inv, d);
#if defined(__BMI2__)
    else if constexpr (N == 2) return divexact1_ip_2(n, inv, d);
#endif
    else return detail_divexact_ip::dispatch<N>(n, inv, d);
}

// ============================================================================
// Peel loop dispatch: uses LLVM-generated asm when available.
// Returns peel count. n is restored to last valid quotient.
// ============================================================================

template<int N>
inline uint32_t divexact1_ip_peel(uint64_t* n, uint64_t inv, uint64_t d) {
#if defined(__x86_64__) && defined(ZFACTOR_HAS_BMI2)
    uint64_t tmp[N];
    if constexpr (N == 2) return divexact1_ip_peel_2(n, inv, d, tmp);
    else if constexpr (N == 3) return divexact1_ip_peel_3(n, inv, d, tmp);
    else if constexpr (N == 4) return divexact1_ip_peel_4(n, inv, d, tmp);
    else if constexpr (N == 5) return divexact1_ip_peel_5(n, inv, d, tmp);
    else if constexpr (N == 6) return divexact1_ip_peel_6(n, inv, d, tmp);
    else if constexpr (N == 7) return divexact1_ip_peel_7(n, inv, d, tmp);
    else if constexpr (N == 8) return divexact1_ip_peel_8(n, inv, d, tmp);
    else
#endif
    {
        // Generic fallback
        uint64_t tmp[N];
        uint32_t e = 0;
        while (true) {
            uint64_t borrow = divexact1_ip<N>(n, inv, d);
            if (borrow != 0) break;
            for (int j = 0; j < N; j++) tmp[j] = n[j];
            ++e;
        }
        if (e > 0)
            for (int j = 0; j < N; j++) n[j] = tmp[j];
        return e;
    }
}

} // namespace zfactor::fixint
