// Generated by tools/fixint/gen_montmul_adcx.py — do not edit.
// Hand-tuned CIOS Montgomery multiplication for N=3..{} using
// mulx + adcx/adox parallel carry chains and lazy memory loads.
#pragma once

#include <cstdint>
#include "../mpn.h"

namespace zfactor::fixint {

// ============================================================================
// montmul_3_adcx — generated by tools/fixint/gen_montmul_adcx.py.
// Hand-tuned CIOS for N=3 using mulx + adcx/adox parallel carry chains.
// Lazy memory loads: a[], b[], mod[] are never held in registers.
// Footprint: 5 t + 3 ptrs + 3 scratch + rdx + r-out = 12 regs (fits 16-GPR).
// ============================================================================
__attribute__((always_inline))
inline void montmul_3_adcx(mpn::limb_t* __restrict__ r,
                           const mpn::limb_t* __restrict__ a,
                           const mpn::limb_t* __restrict__ b,
                           const mpn::limb_t* __restrict__ mod,
                           mpn::limb_t neg_inv) {
    uint64_t t0 = 0, t1 = 0, t2 = 0, t3 = 0, t4 = 0;
    uint64_t lo, hi, zero;

    asm(
        // ==================== Iteration 0 ====================
        // Phase 1: t = a * b[0]
        "movq 0(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq (%[a]), %[t0], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[t2]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "mulxq 16(%[a]), %[lo], %[t3]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "movq $0, %[t4]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "adoxq %[zero], %[t4]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq $0, %[t4]\n\t"
        // ==================== Iteration 1 ====================
        // Phase 1: t += a * b[1]
        "movq 8(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "adoxq %[zero], %[t4]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "adoxq %[zero], %[t4]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq $0, %[t4]\n\t"
        // ==================== Iteration 2 ====================
        // Phase 1: t += a * b[2]
        "movq 16(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "adoxq %[zero], %[t4]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "adcxq %[zero], %[t3]\n\t"
        "adoxq %[zero], %[t4]\n\t"

        : [t0]   "+&r"(t0),
          [t1]   "+&r"(t1),
          [t2]   "+&r"(t2),
          [t3]   "+&r"(t3),
          [t4]   "+&r"(t4),
          [lo]   "=&r"(lo),
          [hi]   "=&r"(hi),
          [zero] "=&r"(zero)
        : [a]      "r"(a),
          [b]      "r"(b),
          [mod]    "r"(mod),
          [inv]    "r"(neg_inv),
          [a_mem]  "m"(*(const uint64_t(*)[3])a),
          [b_mem]  "m"(*(const uint64_t(*)[3])b),
          [m_mem]  "m"(*(const uint64_t(*)[3])mod)
        : "rdx", "cc"
    );

    // Conditional subtract done in a separate asm block — keeps
    // the body block within the 16-GPR budget for higher N.
    uint64_t o0 = t1, o1 = t2, o2 = t3;
    asm(
        "subq (%[mod]), %[t1]\n\t"
        "sbbq 8(%[mod]), %[t2]\n\t"
        "sbbq 16(%[mod]), %[t3]\n\t"
        "sbbq $0, %[t4]\n\t"
        "cmovbq %[o0], %[t1]\n\t"
        "cmovbq %[o1], %[t2]\n\t"
        "cmovbq %[o2], %[t3]\n\t"
        : [t1] "+&r"(t1),
          [t2] "+&r"(t2),
          [t3] "+&r"(t3),
          [t4] "+&r"(t4)
        : [mod] "r"(mod),
          [o0] "r"(o0), [o1] "r"(o1), [o2] "r"(o2),
          [m_mem] "m"(*(const uint64_t(*)[3])mod)
        : "cc"
    );
    r[0] = t1;
    r[1] = t2;
    r[2] = t3;
}


// ============================================================================
// montmul_4_adcx — generated by tools/fixint/gen_montmul_adcx.py.
// Hand-tuned CIOS for N=4 using mulx + adcx/adox parallel carry chains.
// Lazy memory loads: a[], b[], mod[] are never held in registers.
// Footprint: 6 t + 3 ptrs + 3 scratch + rdx + r-out = 13 regs (fits 16-GPR).
// ============================================================================
__attribute__((always_inline))
inline void montmul_4_adcx(mpn::limb_t* __restrict__ r,
                           const mpn::limb_t* __restrict__ a,
                           const mpn::limb_t* __restrict__ b,
                           const mpn::limb_t* __restrict__ mod,
                           mpn::limb_t neg_inv) {
    uint64_t t0 = 0, t1 = 0, t2 = 0, t3 = 0, t4 = 0, t5 = 0;
    uint64_t lo, hi, zero;

    asm(
        // ==================== Iteration 0 ====================
        // Phase 1: t = a * b[0]
        "movq 0(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq (%[a]), %[t0], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[t2]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "mulxq 16(%[a]), %[lo], %[t3]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "mulxq 24(%[a]), %[lo], %[t4]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "movq $0, %[t5]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq $0, %[t5]\n\t"
        // ==================== Iteration 1 ====================
        // Phase 1: t += a * b[1]
        "movq 8(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq $0, %[t5]\n\t"
        // ==================== Iteration 2 ====================
        // Phase 1: t += a * b[2]
        "movq 16(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq $0, %[t5]\n\t"
        // ==================== Iteration 3 ====================
        // Phase 1: t += a * b[3]
        "movq 24(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "adcxq %[zero], %[t4]\n\t"
        "adoxq %[zero], %[t5]\n\t"

        : [t0]   "+&r"(t0),
          [t1]   "+&r"(t1),
          [t2]   "+&r"(t2),
          [t3]   "+&r"(t3),
          [t4]   "+&r"(t4),
          [t5]   "+&r"(t5),
          [lo]   "=&r"(lo),
          [hi]   "=&r"(hi),
          [zero] "=&r"(zero)
        : [a]      "r"(a),
          [b]      "r"(b),
          [mod]    "r"(mod),
          [inv]    "r"(neg_inv),
          [a_mem]  "m"(*(const uint64_t(*)[4])a),
          [b_mem]  "m"(*(const uint64_t(*)[4])b),
          [m_mem]  "m"(*(const uint64_t(*)[4])mod)
        : "rdx", "cc"
    );

    // Conditional subtract done in a separate asm block — keeps
    // the body block within the 16-GPR budget for higher N.
    uint64_t o0 = t1, o1 = t2, o2 = t3, o3 = t4;
    asm(
        "subq (%[mod]), %[t1]\n\t"
        "sbbq 8(%[mod]), %[t2]\n\t"
        "sbbq 16(%[mod]), %[t3]\n\t"
        "sbbq 24(%[mod]), %[t4]\n\t"
        "sbbq $0, %[t5]\n\t"
        "cmovbq %[o0], %[t1]\n\t"
        "cmovbq %[o1], %[t2]\n\t"
        "cmovbq %[o2], %[t3]\n\t"
        "cmovbq %[o3], %[t4]\n\t"
        : [t1] "+&r"(t1),
          [t2] "+&r"(t2),
          [t3] "+&r"(t3),
          [t4] "+&r"(t4),
          [t5] "+&r"(t5)
        : [mod] "r"(mod),
          [o0] "r"(o0), [o1] "r"(o1), [o2] "r"(o2), [o3] "r"(o3),
          [m_mem] "m"(*(const uint64_t(*)[4])mod)
        : "cc"
    );
    r[0] = t1;
    r[1] = t2;
    r[2] = t3;
    r[3] = t4;
}


// ============================================================================
// montmul_5_adcx — generated by tools/fixint/gen_montmul_adcx.py.
// Hand-tuned CIOS for N=5 using mulx + adcx/adox parallel carry chains.
// Lazy memory loads: a[], b[], mod[] are never held in registers.
// Footprint: 7 t + 3 ptrs + 3 scratch + rdx + r-out = 14 regs; `inv` in mem.
// ============================================================================
__attribute__((always_inline))
inline void montmul_5_adcx(mpn::limb_t* __restrict__ r,
                           const mpn::limb_t* __restrict__ a,
                           const mpn::limb_t* __restrict__ b,
                           const mpn::limb_t* __restrict__ mod,
                           mpn::limb_t neg_inv) {
    uint64_t t0 = 0, t1 = 0, t2 = 0, t3 = 0, t4 = 0, t5 = 0, t6 = 0;
    uint64_t lo, hi, zero;

    asm(
        // ==================== Iteration 0 ====================
        // Phase 1: t = a * b[0]
        "movq 0(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq (%[a]), %[t0], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[t2]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "mulxq 16(%[a]), %[lo], %[t3]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "mulxq 24(%[a]), %[lo], %[t4]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "mulxq 32(%[a]), %[lo], %[t5]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "movq $0, %[t6]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq $0, %[t6]\n\t"
        // ==================== Iteration 1 ====================
        // Phase 1: t += a * b[1]
        "movq 8(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq $0, %[t6]\n\t"
        // ==================== Iteration 2 ====================
        // Phase 1: t += a * b[2]
        "movq 16(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq $0, %[t6]\n\t"
        // ==================== Iteration 3 ====================
        // Phase 1: t += a * b[3]
        "movq 24(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq $0, %[t6]\n\t"
        // ==================== Iteration 4 ====================
        // Phase 1: t += a * b[4]
        "movq 32(%[b]), %%rdx\n\t"
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[zero], %k[zero]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "adcxq %[zero], %[t5]\n\t"
        "adoxq %[zero], %[t6]\n\t"

        : [t0]   "+&r"(t0),
          [t1]   "+&r"(t1),
          [t2]   "+&r"(t2),
          [t3]   "+&r"(t3),
          [t4]   "+&r"(t4),
          [t5]   "+&r"(t5),
          [t6]   "+&r"(t6),
          [lo]   "=&r"(lo),
          [hi]   "=&r"(hi),
          [zero] "=&r"(zero)
        : [a]      "r"(a),
          [b]      "r"(b),
          [mod]    "r"(mod),
          [inv]    "m"(neg_inv),
          [a_mem]  "m"(*(const uint64_t(*)[5])a),
          [b_mem]  "m"(*(const uint64_t(*)[5])b),
          [m_mem]  "m"(*(const uint64_t(*)[5])mod)
        : "rdx", "cc"
    );

    // Conditional subtract done in a separate asm block — keeps
    // the body block within the 16-GPR budget for higher N.
    uint64_t o0 = t1, o1 = t2, o2 = t3, o3 = t4, o4 = t5;
    asm(
        "subq (%[mod]), %[t1]\n\t"
        "sbbq 8(%[mod]), %[t2]\n\t"
        "sbbq 16(%[mod]), %[t3]\n\t"
        "sbbq 24(%[mod]), %[t4]\n\t"
        "sbbq 32(%[mod]), %[t5]\n\t"
        "sbbq $0, %[t6]\n\t"
        "cmovbq %[o0], %[t1]\n\t"
        "cmovbq %[o1], %[t2]\n\t"
        "cmovbq %[o2], %[t3]\n\t"
        "cmovbq %[o3], %[t4]\n\t"
        "cmovbq %[o4], %[t5]\n\t"
        : [t1] "+&r"(t1),
          [t2] "+&r"(t2),
          [t3] "+&r"(t3),
          [t4] "+&r"(t4),
          [t5] "+&r"(t5),
          [t6] "+&r"(t6)
        : [mod] "r"(mod),
          [o0] "r"(o0), [o1] "r"(o1), [o2] "r"(o2), [o3] "r"(o3), [o4] "r"(o4),
          [m_mem] "m"(*(const uint64_t(*)[5])mod)
        : "cc"
    );
    r[0] = t1;
    r[1] = t2;
    r[2] = t3;
    r[3] = t4;
    r[4] = t5;
}


// ============================================================================
// montmul_6_adcx — generated by tools/fixint/gen_montmul_adcx.py.
// Hand-tuned CIOS for N=6 using mulx + adcx/adox parallel carry chains.
// Lazy memory loads: a[], b[], mod[] are never held in registers.
// Footprint: 8 t + 3 ptrs + 2 scratch + rdx + r-out = 14 regs; `inv` in mem, no `zero` reg (setc/seto residual capture).
// ============================================================================
__attribute__((always_inline))
inline void montmul_6_adcx(mpn::limb_t* __restrict__ r,
                           const mpn::limb_t* __restrict__ a,
                           const mpn::limb_t* __restrict__ b,
                           const mpn::limb_t* __restrict__ mod,
                           mpn::limb_t neg_inv) {
    uint64_t t0 = 0, t1 = 0, t2 = 0, t3 = 0, t4 = 0, t5 = 0, t6 = 0, t7 = 0;
    uint64_t lo, hi;

    asm(
        // ==================== Iteration 0 ====================
        // Phase 1: t = a * b[0]
        "movq 0(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq (%[a]), %[t0], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[t2]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "mulxq 16(%[a]), %[lo], %[t3]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "mulxq 24(%[a]), %[lo], %[t4]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "mulxq 32(%[a]), %[lo], %[t5]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "mulxq 40(%[a]), %[lo], %[t6]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "setc %b[lo]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "addq %[lo], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq %[t7], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // ==================== Iteration 1 ====================
        // Phase 1: t += a * b[1]
        "movq 8(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq %[t7], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // ==================== Iteration 2 ====================
        // Phase 1: t += a * b[2]
        "movq 16(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq %[t7], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // ==================== Iteration 3 ====================
        // Phase 1: t += a * b[3]
        "movq 24(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq %[t7], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // ==================== Iteration 4 ====================
        // Phase 1: t += a * b[4]
        "movq 32(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Shift t down by 64 bits (mov-elim makes this free)
        "movq %[t1], %[t0]\n\t"
        "movq %[t2], %[t1]\n\t"
        "movq %[t3], %[t2]\n\t"
        "movq %[t4], %[t3]\n\t"
        "movq %[t5], %[t4]\n\t"
        "movq %[t6], %[t5]\n\t"
        "movq %[t7], %[t6]\n\t"
        "movq $0, %[t7]\n\t"
        // ==================== Iteration 5 ====================
        // Phase 1: t += a * b[5]
        "movq 40(%[b]), %%rdx\n\t"
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[a]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"
        // Phase 2: m = t[0] * neg_inv (rdx = m for next mulx chain)
        "movq %[t0], %%rdx\n\t"
        "imulq %[inv], %%rdx\n\t"
        // Phase 3: t += mod * m  (t[0] -> 0)
        "xorl %k[lo], %k[lo]\n\t"
        "mulxq 0(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t0]\n\t"
        "adoxq %[hi], %[t1]\n\t"
        "mulxq 8(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t1]\n\t"
        "adoxq %[hi], %[t2]\n\t"
        "mulxq 16(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t2]\n\t"
        "adoxq %[hi], %[t3]\n\t"
        "mulxq 24(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t3]\n\t"
        "adoxq %[hi], %[t4]\n\t"
        "mulxq 32(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t4]\n\t"
        "adoxq %[hi], %[t5]\n\t"
        "mulxq 40(%[mod]), %[lo], %[hi]\n\t"
        "adcxq %[lo], %[t5]\n\t"
        "adoxq %[hi], %[t6]\n\t"
        "setc %b[lo]\n\t"
        "seto %b[hi]\n\t"
        "movzbq %b[lo], %[lo]\n\t"
        "movzbq %b[hi], %[hi]\n\t"
        "addq %[lo], %[t6]\n\t"
        "addq %[hi], %[t7]\n\t"

        : [t0]   "+&r"(t0),
          [t1]   "+&r"(t1),
          [t2]   "+&r"(t2),
          [t3]   "+&r"(t3),
          [t4]   "+&r"(t4),
          [t5]   "+&r"(t5),
          [t6]   "+&r"(t6),
          [t7]   "+&r"(t7),
          [lo]   "=&Q"(lo),
          [hi]   "=&Q"(hi)
        : [a]      "r"(a),
          [b]      "r"(b),
          [mod]    "r"(mod),
          [inv]    "m"(neg_inv),
          [a_mem]  "m"(*(const uint64_t(*)[6])a),
          [b_mem]  "m"(*(const uint64_t(*)[6])b),
          [m_mem]  "m"(*(const uint64_t(*)[6])mod)
        : "rdx", "cc"
    );

    // Conditional subtract done in a separate asm block — keeps
    // the body block within the 16-GPR budget for higher N.
    uint64_t o0 = t1, o1 = t2, o2 = t3, o3 = t4, o4 = t5, o5 = t6;
    asm(
        "subq (%[mod]), %[t1]\n\t"
        "sbbq 8(%[mod]), %[t2]\n\t"
        "sbbq 16(%[mod]), %[t3]\n\t"
        "sbbq 24(%[mod]), %[t4]\n\t"
        "sbbq 32(%[mod]), %[t5]\n\t"
        "sbbq 40(%[mod]), %[t6]\n\t"
        "sbbq $0, %[t7]\n\t"
        "cmovbq %[o0], %[t1]\n\t"
        "cmovbq %[o1], %[t2]\n\t"
        "cmovbq %[o2], %[t3]\n\t"
        "cmovbq %[o3], %[t4]\n\t"
        "cmovbq %[o4], %[t5]\n\t"
        "cmovbq %[o5], %[t6]\n\t"
        : [t1] "+&r"(t1),
          [t2] "+&r"(t2),
          [t3] "+&r"(t3),
          [t4] "+&r"(t4),
          [t5] "+&r"(t5),
          [t6] "+&r"(t6),
          [t7] "+&r"(t7)
        : [mod] "r"(mod),
          [o0] "r"(o0), [o1] "r"(o1), [o2] "r"(o2), [o3] "r"(o3), [o4] "r"(o4), [o5] "r"(o5),
          [m_mem] "m"(*(const uint64_t(*)[6])mod)
        : "cc"
    );
    r[0] = t1;
    r[1] = t2;
    r[2] = t3;
    r[3] = t4;
    r[4] = t5;
    r[5] = t6;
}


} // namespace zfactor::fixint