#pragma once

// Generated by tools/fixint/gen_mpn.py. Do not edit by hand.

#define ZFACTOR_MPN_DECLARE_ONLY 1
#include "mpn_generic.h"
#undef ZFACTOR_MPN_DECLARE_ONLY

namespace zfactor::fixint::mpn {

template<int B>
__attribute__((always_inline)) inline uint8_t add_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_add_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline uint8_t add_block(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    return generic_add_block<B>(r, a, b, cy);
}

template<int B>
__attribute__((always_inline)) inline uint8_t sub_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_sub_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline uint8_t sub_block(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    return generic_sub_block<B>(r, a, b, bw);
}

template<int B>
__attribute__((always_inline)) inline limb_t addmul1_block(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
    return generic_addmul1_block<B>(r, a, scalar, cy);
}

template<int N>
__attribute__((always_inline)) inline bool sqr_small_asm(limb_t* r, const limb_t* a) {
    (void)r;
    (void)a;
    return false;
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<1>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<1>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<2>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<2>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<3>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<3>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<4>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<4>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<5>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<5>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<6>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<6>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<7>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<7>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}


template<>
__attribute__((always_inline)) inline uint8_t add_block_first<8>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t carry, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "addq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "adcq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t add_block<8>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        "negq %[cy]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "adcq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "adcq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "adcq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "adcq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "adcq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "adcq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "adcq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "adcq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[cy], %[cy]\n\t"
        "negq %[cy]\n\t"
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<1>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<1>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<2>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<2>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<3>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<3>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<4>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<4>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<5>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<5>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<6>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<6>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<7>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<7>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}


template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<8>(limb_t* r, const limb_t* a, const limb_t* b) {
    limb_t borrow, t;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t]\n\t"
        "subq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "sbbq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<8>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        "negq %[bw]\n\t"
        "movq 0(%[a]), %[t]\n\t"
        "sbbq 0(%[b]), %[t]\n\t"
        "movq %[t], 0(%[r])\n\t"
        "movq 8(%[a]), %[t]\n\t"
        "sbbq 8(%[b]), %[t]\n\t"
        "movq %[t], 8(%[r])\n\t"
        "movq 16(%[a]), %[t]\n\t"
        "sbbq 16(%[b]), %[t]\n\t"
        "movq %[t], 16(%[r])\n\t"
        "movq 24(%[a]), %[t]\n\t"
        "sbbq 24(%[b]), %[t]\n\t"
        "movq %[t], 24(%[r])\n\t"
        "movq 32(%[a]), %[t]\n\t"
        "sbbq 32(%[b]), %[t]\n\t"
        "movq %[t], 32(%[r])\n\t"
        "movq 40(%[a]), %[t]\n\t"
        "sbbq 40(%[b]), %[t]\n\t"
        "movq %[t], 40(%[r])\n\t"
        "movq 48(%[a]), %[t]\n\t"
        "sbbq 48(%[b]), %[t]\n\t"
        "movq %[t], 48(%[r])\n\t"
        "movq 56(%[a]), %[t]\n\t"
        "sbbq 56(%[b]), %[t]\n\t"
        "movq %[t], 56(%[r])\n\t"
        "sbbq %[bw], %[bw]\n\t"
        "negq %[bw]\n\t"
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}

template<>
__attribute__((always_inline)) inline void lshift_small<1>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<1>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<2>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<2>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<3>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<3>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<4>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 24(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<4>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 24(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<5>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 32(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 24(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<5>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 24(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 32(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<6>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 40(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 32(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 24(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<6>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 24(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 32(%[r])\n\t"
        "movq 40(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 40(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<7>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 40(%[a]), %[t0]\n\t"
        "movq 48(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 48(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 40(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 32(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 24(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<7>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 24(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 32(%[r])\n\t"
        "movq 40(%[a]), %[t0]\n\t"
        "movq 48(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 40(%[r])\n\t"
        "movq 48(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 48(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}


template<>
__attribute__((always_inline)) inline void lshift_small<8>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 48(%[a]), %[t0]\n\t"
        "movq 56(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 56(%[r])\n\t"
        "movq 40(%[a]), %[t0]\n\t"
        "movq 48(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 48(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 40(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 32(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 24(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 16(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shldq %%cl, %[t0], %[t1]\n\t"
        "movq %[t1], 8(%[r])\n\t"
        "movq 0(%[a]), %[t0]\n\t"
        "shlq %%cl, %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline void rshift_small<8>(limb_t* r, const limb_t* a, unsigned bits) {
    limb_t t0, t1;
    __asm__ __volatile__(
        "movq 0(%[a]), %[t0]\n\t"
        "movq 8(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 0(%[r])\n\t"
        "movq 8(%[a]), %[t0]\n\t"
        "movq 16(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 8(%[r])\n\t"
        "movq 16(%[a]), %[t0]\n\t"
        "movq 24(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 16(%[r])\n\t"
        "movq 24(%[a]), %[t0]\n\t"
        "movq 32(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 24(%[r])\n\t"
        "movq 32(%[a]), %[t0]\n\t"
        "movq 40(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 32(%[r])\n\t"
        "movq 40(%[a]), %[t0]\n\t"
        "movq 48(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 40(%[r])\n\t"
        "movq 48(%[a]), %[t0]\n\t"
        "movq 56(%[a]), %[t1]\n\t"
        "shrdq %%cl, %[t1], %[t0]\n\t"
        "movq %[t0], 48(%[r])\n\t"
        "movq 56(%[a]), %[t0]\n\t"
        "shrq %%cl, %[t0]\n\t"
        "movq %[t0], 56(%[r])\n\t"
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<1>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[co]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[co]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<1>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<2>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[co]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<2>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<3>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[co]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[co]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<3>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<4>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 24(%[a]), %[t0], %[co]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<4>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<5>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "mulx 32(%[a]), %[t0], %[co]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 32(%[a]), %[t0], %[co]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<5>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<6>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "mulx 40(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 40(%[a]), %[t0], %[co]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<6>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<7>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "mulx 40(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "mulx 48(%[a]), %[t0], %[co]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 48(%[r]), %[t0]\n\t"
            "movq %[t0], 48(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 40(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 48(%[a]), %[t0], %[co]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 48(%[r]), %[t0]\n\t"
            "movq %[t0], 48(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<7>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline limb_t addmul1_block<8>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "xorl %%eax, %%eax\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "adox %[ci], %[t0]\n\t"
            "adcx 0(%[r]), %[t0]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "mulx 40(%[a]), %[t0], %[t2]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "mulx 48(%[a]), %[t0], %[t1]\n\t"
            "adox %[t2], %[t0]\n\t"
            "adcx 48(%[r]), %[t0]\n\t"
            "movq %[t0], 48(%[r])\n\t"
            "mulx 56(%[a]), %[t0], %[co]\n\t"
            "adox %[t1], %[t0]\n\t"
            "adcx 56(%[r]), %[t0]\n\t"
            "movq %[t0], 56(%[r])\n\t"
            "movq $0, %[t0]\n\t"
            "adox %[t0], %[co]\n\t"
            "adcx %[t0], %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\n\t"
            "mulx 0(%[a]), %[t0], %[t1]\n\t"
            "addq 0(%[r]), %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "addq %[ci], %[t0]\n\t"
            "adcq $0, %[t1]\n\t"
            "movq %[t0], 0(%[r])\n\t"
            "mulx 8(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 8(%[r]), %[t0]\n\t"
            "movq %[t0], 8(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 16(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 16(%[r]), %[t0]\n\t"
            "movq %[t0], 16(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 24(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 24(%[r]), %[t0]\n\t"
            "movq %[t0], 24(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 32(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 32(%[r]), %[t0]\n\t"
            "movq %[t0], 32(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 40(%[a]), %[t0], %[t2]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 40(%[r]), %[t0]\n\t"
            "movq %[t0], 40(%[r])\n\t"
            "adcq $0, %[t2]\n\t"
            "mulx 48(%[a]), %[t0], %[t1]\n\t"
            "addq %[t2], %[t0]\n\t"
            "adcq 48(%[r]), %[t0]\n\t"
            "movq %[t0], 48(%[r])\n\t"
            "adcq $0, %[t1]\n\t"
            "mulx 56(%[a]), %[t0], %[co]\n\t"
            "addq %[t1], %[t0]\n\t"
            "adcq 56(%[r]), %[t0]\n\t"
            "movq %[t0], 56(%[r])\n\t"
            "adcq $0, %[co]\n\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
#else
    return generic_addmul1_block<8>(r, a, scalar, cy);
#endif
}

template<>
__attribute__((always_inline)) inline bool sqr_small_asm<2>(limb_t* r, const limb_t* a) {
#if defined(ZFACTOR_HAS_BMI2)
    __asm__ __volatile__(
        "movq 0(%[a]), %%rdx\n\t"
        "mulx 8(%[a]), %%r8, %%r9\n\t"
        "mulx 0(%[a]), %%rax, %%r10\n\t"
        "movq 8(%[a]), %%rdx\n\t"
        "mulx 8(%[a]), %%r11, %%rbx\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%r8, %%r8\n\t"
        "adcq %%r9, %%r9\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%r8, %%r10\n\t"
        "adcq %%r11, %%r9\n\t"
        "adcq %%rcx, %%rbx\n\t"
        "movq %%rax, 0(%[r])\n\t"
        "movq %%r10, 8(%[r])\n\t"
        "movq %%r9, 16(%[r])\n\t"
        "movq %%rbx, 24(%[r])\n\t"
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rbx", "rcx", "rdx", "r8", "r9", "r10", "r11", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}

template<>
__attribute__((always_inline)) inline bool sqr_small_asm<3>(limb_t* r, const limb_t* a) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    __asm__ __volatile__(
        "movq 0(%[a]), %%rdx\n\t"
        "mulx 8(%[a]), %%r10, %%r11\n\t"
        "mulx 16(%[a]), %%r8, %%r9\n\t"
        "addq %%r11, %%r8\n\t"
        "movq 8(%[a]), %%rdx\n\t"
        "mulx 16(%[a]), %%rax, %%r11\n\t"
        "adcq %%rax, %%r9\n\t"
        "adcq $0, %%r11\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "movq 0(%[a]), %%rdx\n\t"
        "mulx 0(%[a]), %%rbx, %%rax\n\t"
        "movq %%rbx, 0(%[r])\n\t"
        "movq 8(%[a]), %%rdx\n\t"
        "mulx 8(%[a]), %%r14, %%r15\n\t"
        "movq 16(%[a]), %%rdx\n\t"
        "mulx 16(%[a]), %%rsi, %%rdx\n\t"
        "adcx %%r10, %%r10\n\t"
        "adcx %%r8, %%r8\n\t"
        "adcx %%r9, %%r9\n\t"
        "adcx %%r11, %%r11\n\t"
        "adox %%r10, %%rax\n\t"
        "adox %%r8, %%r14\n\t"
        "adox %%r9, %%r15\n\t"
        "adox %%r11, %%rsi\n\t"
        "adox %%rcx, %%rdx\n\t"
        "adcx %%rcx, %%rdx\n\t"
        "movq %%rax, 8(%[r])\n\t"
        "movq %%r14, 16(%[r])\n\t"
        "movq %%r15, 24(%[r])\n\t"
        "movq %%rsi, 32(%[r])\n\t"
        "movq %%rdx, 40(%[r])\n\t"
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rbx", "rcx", "rdx", "r8", "r9", "r10", "r11",
          "r14", "r15", "rsi", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}

template<>
__attribute__((always_inline)) inline bool sqr_small_asm<4>(limb_t* r, const limb_t* a) {
#if defined(__x86_64__)
    __asm__ __volatile__(
        "xorq %%r8, %%r8\n\t"
        "xorq %%r9, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 0(%[a]), %%rax\n\t"
        "mulq 0(%[a])\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq $0, %%r10\n\t"
        "movq %%r8, 0(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 0(%[a]), %%rax\n\t"
        "mulq 8(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq %%r8, 8(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 0(%[a]), %%rax\n\t"
        "mulq 16(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq 8(%[a]), %%rax\n\t"
        "mulq 8(%[a])\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq $0, %%r10\n\t"
        "movq %%r8, 16(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 0(%[a]), %%rax\n\t"
        "mulq 24(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq 8(%[a]), %%rax\n\t"
        "mulq 16(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq %%r8, 24(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 8(%[a]), %%rax\n\t"
        "mulq 24(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq 16(%[a]), %%rax\n\t"
        "mulq 16(%[a])\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq $0, %%r10\n\t"
        "movq %%r8, 32(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 16(%[a]), %%rax\n\t"
        "mulq 24(%[a])\n\t"
        "xorq %%rcx, %%rcx\n\t"
        "addq %%rax, %%rax\n\t"
        "adcq %%rdx, %%rdx\n\t"
        "adcq $0, %%rcx\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq %%rcx, %%r10\n\t"
        "movq %%r8, 40(%[r])\n\t"
        "movq %%r9, %%r8\n\t"
        "movq %%r10, %%r9\n\t"
        "xorq %%r10, %%r10\n\t"
        "movq 24(%[a]), %%rax\n\t"
        "mulq 24(%[a])\n\t"
        "addq %%rax, %%r8\n\t"
        "adcq %%rdx, %%r9\n\t"
        "adcq $0, %%r10\n\t"
        "movq %%r8, 48(%[r])\n\t"
        "movq %%r9, 56(%[r])\n\t"
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rcx", "rdx", "r8", "r9", "r10", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t add_chunked(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    if constexpr (N <= B) {
        return add_block<N>(r, a, b, cy);
    } else {
        cy = add_block<B>(r, a, b, cy);
        return add_chunked<N - B, B>(r + B, a + B, b + B, cy);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t add_chunked_first(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= B) {
        return add_block_first<N>(r, a, b);
    } else {
        uint8_t cy = add_block_first<B>(r, a, b);
        return add_chunked<N - B, B>(r + B, a + B, b + B, cy);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t sub_chunked(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    if constexpr (N <= B) {
        return sub_block<N>(r, a, b, bw);
    } else {
        bw = sub_block<B>(r, a, b, bw);
        return sub_chunked<N - B, B>(r + B, a + B, b + B, bw);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t sub_chunked_first(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= B) {
        return sub_block_first<N>(r, a, b);
    } else {
        uint8_t bw = sub_block_first<B>(r, a, b);
        return sub_chunked<N - B, B>(r + B, a + B, b + B, bw);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline limb_t addmul1_chunked(limb_t* r, const limb_t* a, limb_t b, limb_t cy) {
    if constexpr (N <= B) {
        return addmul1_block<N>(r, a, b, cy);
    } else {
        cy = addmul1_block<B>(r, a, b, cy);
        return addmul1_chunked<N - B, B>(r + B, a + B, b, cy);
    }
}

template<int N>
__attribute__((always_inline)) inline uint8_t add(limb_t* r, const limb_t* a, const limb_t* b) {
    return add_chunked_first<N, 8>(r, a, b);
}

template<int N>
__attribute__((always_inline)) inline uint8_t sub(limb_t* r, const limb_t* a, const limb_t* b) {
    return sub_chunked_first<N, 8>(r, a, b);
}

template<int N>
__attribute__((always_inline)) inline limb_t addmul1(limb_t* r, const limb_t* a, limb_t b) {
    return addmul1_chunked<N, 8>(r, a, b, 0);
}

} // namespace zfactor::fixint::mpn

#include "mpn_common.h"
