#!/usr/bin/env python3
"""Generate inline-asm divexact1 kernels for N=3..8.

divexact1_N(dst, src, inv, d) -> borrow:
  dst[0..N-1] = src[0..N-1] / d  (exact division, d odd)
  returns 0 if exact, nonzero otherwise.

Algorithm per limb i:
  s = src[i] - borrow_from_prev    (sub, sets CF)
  sub_borrow = CF                   (captured via sbb into temp reg)
  q = s * inv                       (mulx with inv in rdx, lo = quotient)
  dst[i] = q
  borrow = hi(q * d) + sub_borrow  (mulx with d in rdx, hi = new borrow)

Registers: dst, src, inv, d = 4 input ptrs/values
           borrow, q, s = 3 scratch
           rdx = alternates between inv and d

Requires BMI2 (mulx).
"""

import argparse
from pathlib import Path


def gen_divexact1_ip(n: int) -> str:
    """Generate in-place divexact: n /= d, returns borrow."""
    lines = []
    a = lines.append

    fname = f"divexact1_ip_{n}"
    a(f"// N={n} in-place divexact1 — generated by gen_divexact1.py")
    a(f"__attribute__((always_inline))")
    a(f"inline uint64_t {fname}(uint64_t* n, uint64_t inv, uint64_t d) {{")
    a(f"    uint64_t borrow, q, s;")
    a(f"    asm volatile(")

    for i in range(n):
        a(f'        // --- limb {i} ---')
        if i == 0:
            a(f'        "movq %[inv], %%rdx\\n\\t"')
            a(f'        "mulxq (%[n]), %[q], %[s]\\n\\t"')
            a(f'        "movq %[q], (%[n])\\n\\t"')
            a(f'        "movq %[d], %%rdx\\n\\t"')
            a(f'        "mulxq %[q], %[s], %[borrow]\\n\\t"')
        else:
            a(f'        "movq {8*i}(%[n]), %[s]\\n\\t"')
            a(f'        "subq %[borrow], %[s]\\n\\t"')
            a(f'        "sbbq %[q], %[q]\\n\\t"')
            a(f'        "negq %[q]\\n\\t"')
            a(f'        "movq %[inv], %%rdx\\n\\t"')
            a(f'        "mulxq %[s], %[s], %[borrow]\\n\\t"')
            a(f'        "movq %[s], {8*i}(%[n])\\n\\t"')
            a(f'        "movq %[d], %%rdx\\n\\t"')
            a(f'        "mulxq %[s], %[s], %[borrow]\\n\\t"')
            a(f'        "addq %[q], %[borrow]\\n\\t"')

    a(f'        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)')
    a(f'        : [n] "r"(n), [inv] "r"(inv), [d] "r"(d)')
    a(f'        : "rdx", "cc", "memory"')
    a(f"    );")
    a(f"    return borrow;")
    a(f"}}")
    return "\n".join(lines)


def gen_divexact1(n: int) -> str:
    """Generate out-of-place divexact: dst = src / d, returns borrow."""
    lines = []
    a = lines.append

    fname = f"divexact1_{n}"
    a(f"// N={n} divexact1 — generated by gen_divexact1.py")
    a(f"__attribute__((always_inline))")
    a(f"inline uint64_t {fname}(uint64_t* dst,")
    a(f"                        const uint64_t* src,")
    a(f"                        uint64_t inv, uint64_t d) {{")
    a(f"    uint64_t borrow, q, s;")
    a(f"    asm volatile(")

    for i in range(n):
        a(f'        // --- limb {i} ---')
        if i == 0:
            # First limb: no incoming borrow
            # q = src[0] * inv (lo); borrow = hi(q * d)
            a(f'        "movq %[inv], %%rdx\\n\\t"')
            a(f'        "mulxq (%[src]), %[q], %[s]\\n\\t"')         # (s_trash, q) = src[0] * inv
            a(f'        "movq %[q], (%[dst])\\n\\t"')                 # dst[0] = q
            a(f'        "movq %[d], %%rdx\\n\\t"')
            a(f'        "mulxq %[q], %[s], %[borrow]\\n\\t"')        # (borrow, s_trash) = q * d
        else:
            # Subsequent limbs:
            #   s = src[i] - borrow          (sub, CF = sub_borrow)
            #   save CF into q via sbb+neg   (q = 0 or 1)
            #   quotient = s * inv           (mulx, lo = quotient in s)
            #   dst[i] = quotient
            #   borrow = hi(quotient * d) + q
            a(f'        "movq {8*i}(%[src]), %[s]\\n\\t"')
            a(f'        "subq %[borrow], %[s]\\n\\t"')               # s = src[i] - borrow; CF = sub_borrow
            a(f'        "sbbq %[q], %[q]\\n\\t"')                    # q = -CF (0 or -1)
            a(f'        "negq %[q]\\n\\t"')                           # q = 0 or 1 = sub_borrow saved
            a(f'        "movq %[inv], %%rdx\\n\\t"')
            a(f'        "mulxq %[s], %[s], %[borrow]\\n\\t"')        # (borrow_trash, s=quotient) = s * inv
            a(f'        "movq %[s], {8*i}(%[dst])\\n\\t"')           # dst[i] = quotient
            a(f'        "movq %[d], %%rdx\\n\\t"')
            a(f'        "mulxq %[s], %[s], %[borrow]\\n\\t"')        # (borrow, s_trash) = quotient * d
            a(f'        "addq %[q], %[borrow]\\n\\t"')               # borrow += sub_borrow

    a(f'        : [borrow] "=&r"(borrow), [q] "=&r"(q), [s] "=&r"(s)')
    a(f'        : [dst] "r"(dst), [src] "r"(src), [inv] "r"(inv), [d] "r"(d)')
    a(f'        : "rdx", "cc", "memory"')
    a(f"    );")
    a(f"    return borrow;")
    a(f"}}")
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--min-n", type=int, default=3)
    parser.add_argument("--max-n", type=int, default=8)
    args = parser.parse_args()

    parts = [
        "// Generated by tools/fixint/gen_divexact1.py — do not edit.",
        "// Included inside namespace zfactor::fixint, guarded by __BMI2__.",
        "",
    ]

    for n in range(args.min_n, args.max_n + 1):
        parts.append(gen_divexact1_ip(n))
        parts.append("")
        parts.append(gen_divexact1(n))
        parts.append("")

    out = Path(args.output)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(parts))
    print(f"Generated {out} (N={args.min_n}..{args.max_n})")


if __name__ == "__main__":
    main()
