#!/usr/bin/env python3
"""Generate LLVM IR for all-in-one Möller-Granlund basecase divrem.

Single function, no helpers. Caller passes raw (unnormalized) inputs;
the IR handles normalization, the MG basecase loop, and denormalization.

Output: divrem_ir.ll → opt -O3 + llc -O3 → divrem_x86_64.S
"""
import argparse
from pathlib import Path

IR = r'''; Generated by tools/fixint/gen_divrem_ir.py — do not edit.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

declare i64 @llvm.ctlz.i64(i64, i1) nounwind readnone

; ============================================================================
; All-in-one Möller-Granlund basecase divrem.
;
;   void zfactor_mg_divrem(
;       uint64_t       *qp,    // [un - vn + 1] quotient
;       uint64_t       *rp,    // [vn] remainder
;       const uint64_t *up,    // [un] dividend (raw, unnormalized)
;       int64_t         un,
;       const uint64_t *vp,    // [vn] divisor (raw, unnormalized)
;       int64_t         vn);
;
; Preconditions: vn >= 1, un >= vn, vp[vn-1] != 0.
; Caller must short-circuit u < v cases.
; ============================================================================

define void @zfactor_mg_divrem(
    ptr noalias %qp,
    ptr noalias %rp,
    ptr noalias readonly %up,
    i64 %un,
    ptr noalias readonly %vp,
    i64 %vn) #0 {
entry:
  %vn_m1 = sub i64 %vn, 1
  %vtop_raw_ptr = getelementptr i64, ptr %vp, i64 %vn_m1
  %vtop_raw = load i64, ptr %vtop_raw_ptr
  %shift = call i64 @llvm.ctlz.i64(i64 %vtop_raw, i1 true)
  %neg_shift = sub i64 64, %shift
  %has_shift = icmp ne i64 %shift, 0

  ; Stack-allocate work[un+2] and vshift[vn]
  %un_p2 = add i64 %un, 2
  %work = alloca i64, i64 %un_p2, align 8
  %vshift = alloca i64, i64 %vn, align 8

  br label %vshift_loop

  ; ===== Shift v left by `shift` into vshift =====
vshift_loop:
  %vsi = phi i64 [0, %entry], [%vsi_n, %vshift_body]
  %vsp = phi i64 [0, %entry], [%vsl, %vshift_body]
  %vs_done = icmp eq i64 %vsi, %vn
  br i1 %vs_done, label %ushift_loop, label %vshift_body

vshift_body:
  %vsr = getelementptr i64, ptr %vp, i64 %vsi
  %vsl = load i64, ptr %vsr
  %vsl_lo = shl i64 %vsl, %shift
  %vsp_hi = lshr i64 %vsp, %neg_shift
  %vsl_with = or i64 %vsl_lo, %vsp_hi
  %vsl_out = select i1 %has_shift, i64 %vsl_with, i64 %vsl
  %vsd = getelementptr i64, ptr %vshift, i64 %vsi
  store i64 %vsl_out, ptr %vsd
  %vsi_n = add i64 %vsi, 1
  br label %vshift_loop

  ; ===== Shift u left by `shift` into work =====
ushift_loop:
  %usi = phi i64 [0, %vshift_loop], [%usi_n, %ushift_body]
  %usp = phi i64 [0, %vshift_loop], [%usl, %ushift_body]
  %us_done = icmp eq i64 %usi, %un
  br i1 %us_done, label %ushift_finish, label %ushift_body

ushift_body:
  %usr = getelementptr i64, ptr %up, i64 %usi
  %usl = load i64, ptr %usr
  %usl_lo = shl i64 %usl, %shift
  %usp_hi = lshr i64 %usp, %neg_shift
  %usl_with = or i64 %usl_lo, %usp_hi
  %usl_out = select i1 %has_shift, i64 %usl_with, i64 %usl
  %usd = getelementptr i64, ptr %work, i64 %usi
  store i64 %usl_out, ptr %usd
  %usi_n = add i64 %usi, 1
  br label %ushift_loop

ushift_finish:
  ; spillover = u[un-1] >> (64-shift) if has_shift else 0
  %un_m1 = sub i64 %un, 1
  %u_last_ptr = getelementptr i64, ptr %up, i64 %un_m1
  %u_last_val = load i64, ptr %u_last_ptr
  %spill_hi = lshr i64 %u_last_val, %neg_shift
  %spillover = select i1 %has_shift, i64 %spill_hi, i64 0
  %work_top = getelementptr i64, ptr %work, i64 %un
  store i64 %spillover, ptr %work_top
  %work_pad_idx = add i64 %un, 1
  %work_pad = getelementptr i64, ptr %work, i64 %work_pad_idx
  store i64 0, ptr %work_pad

  ; v_recip = floor((B^2 - 1) / vshift[vn-1]) - B   (the MG reciprocal)
  ; Compute via single divq: (~d:~0) / d. For normalized d, ~d < d so no overflow.
  %v_top_ptr = getelementptr i64, ptr %vshift, i64 %vn_m1
  %v_top = load i64, ptr %v_top_ptr
  %not_v_top = xor i64 %v_top, -1
  %v_recip = call i64 asm sideeffect "divq $3",
    "={ax},{ax},{dx},r,~{dx},~{cc}"
    (i64 -1, i64 %not_v_top, i64 %v_top)

  ; un_eff = un + (spillover != 0 ? 1 : 0)
  %has_spill = icmp ne i64 %spillover, 0
  %un_p1 = add i64 %un, 1
  %un_eff = select i1 %has_spill, i64 %un_p1, i64 %un

  %is_single = icmp eq i64 %vn, 1
  br i1 %is_single, label %s_init, label %m_init

  ; ===== Single-limb divrem =====
s_init:
  br label %s_loop

s_loop:
  %s_i = phi i64 [%un, %s_init], [%s_id, %s_body]
  %s_rem = phi i64 [%spillover, %s_init], [%s_rn, %s_body]
  %s_done = icmp eq i64 %s_i, 0
  br i1 %s_done, label %s_finish, label %s_body

s_body:
  %s_id = sub i64 %s_i, 1
  %s_u_ptr = getelementptr i64, ptr %work, i64 %s_id
  %s_u = load i64, ptr %s_u_ptr
  %s_remw = zext i64 %s_rem to i128
  %s_recw = zext i64 %v_recip to i128
  %s_t = mul i128 %s_remw, %s_recw
  %s_uw = zext i64 %s_u to i128
  %s_remhi = shl i128 %s_remw, 64
  %s_uful = or i128 %s_remhi, %s_uw
  %s_tu = add i128 %s_t, %s_uful
  %s_q1pw = lshr i128 %s_tu, 64
  %s_q1p = trunc i128 %s_q1pw to i64
  %s_q1 = add i64 %s_q1p, 1
  %s_q0 = trunc i128 %s_tu to i64
  %s_qd = mul i64 %s_q1, %v_top
  %s_r0 = sub i64 %s_u, %s_qd
  %s_n_c1 = icmp ugt i64 %s_r0, %s_q0
  %s_q_c1 = select i1 %s_n_c1, i64 %s_q1p, i64 %s_q1
  %s_r0pd = add i64 %s_r0, %v_top
  %s_r_c1 = select i1 %s_n_c1, i64 %s_r0pd, i64 %s_r0
  %s_n_c2 = icmp uge i64 %s_r_c1, %v_top
  %s_q_c2 = add i64 %s_q_c1, 1
  %s_q_n = select i1 %s_n_c2, i64 %s_q_c2, i64 %s_q_c1
  %s_r_md = sub i64 %s_r_c1, %v_top
  %s_rn = select i1 %s_n_c2, i64 %s_r_md, i64 %s_r_c1
  %s_q_dst = getelementptr i64, ptr %qp, i64 %s_id
  store i64 %s_q_n, ptr %s_q_dst
  br label %s_loop

s_finish:
  store i64 %s_rem, ptr %work
  %work_1 = getelementptr i64, ptr %work, i64 1
  store i64 0, ptr %work_1
  br label %denorm_loop

  ; ===== Multi-limb divrem (vn >= 2) =====
m_init:
  %vn_m2 = sub i64 %vn, 2
  %v_top2_ptr = getelementptr i64, ptr %vshift, i64 %vn_m2
  %v_top2 = load i64, ptr %v_top2_ptr
  %j_init = sub i64 %un_eff, %vn
  br label %m_loop

m_loop:
  %j = phi i64 [%j_init, %m_init], [%j_dec, %m_after]
  %j_done = icmp slt i64 %j, 0
  br i1 %j_done, label %denorm_loop, label %m_body

m_body:
  %j_p_vn = add i64 %j, %vn
  %j_p_vn_m1 = sub i64 %j_p_vn, 1
  %j_p_vn_m2 = sub i64 %j_p_vn, 2
  %ut_ptr = getelementptr i64, ptr %work, i64 %j_p_vn
  %ut = load i64, ptr %ut_ptr
  %ut1_ptr = getelementptr i64, ptr %work, i64 %j_p_vn_m1
  %ut1 = load i64, ptr %ut1_ptr
  %ut2_ptr = getelementptr i64, ptr %work, i64 %j_p_vn_m2
  %ut2 = load i64, ptr %ut2_ptr

  %sat = icmp uge i64 %ut, %v_top
  br i1 %sat, label %qhat_sat, label %qhat_normal

qhat_sat:
  %qh_s = sub i64 0, 1
  %rh_s = add i64 %ut, %ut1
  %rh_ovf = icmp ult i64 %rh_s, %ut
  br label %refine_check

qhat_normal:
  %qn_utw = zext i64 %ut to i128
  %qn_recw = zext i64 %v_recip to i128
  %qn_t = mul i128 %qn_utw, %qn_recw
  %qn_ut1w = zext i64 %ut1 to i128
  %qn_uthi = shl i128 %qn_utw, 64
  %qn_uful = or i128 %qn_uthi, %qn_ut1w
  %qn_tu = add i128 %qn_t, %qn_uful
  %qn_q1pw = lshr i128 %qn_tu, 64
  %qn_q1p = trunc i128 %qn_q1pw to i64
  %qn_q1 = add i64 %qn_q1p, 1
  %qn_q0 = trunc i128 %qn_tu to i64
  %qn_qd = mul i64 %qn_q1, %v_top
  %qn_r0 = sub i64 %ut1, %qn_qd
  %qn_n_c1 = icmp ugt i64 %qn_r0, %qn_q0
  %qn_q_c1 = select i1 %qn_n_c1, i64 %qn_q1p, i64 %qn_q1
  %qn_r0pd = add i64 %qn_r0, %v_top
  %qn_r_c1 = select i1 %qn_n_c1, i64 %qn_r0pd, i64 %qn_r0
  %qn_n_c2 = icmp uge i64 %qn_r_c1, %v_top
  %qn_q_c2 = add i64 %qn_q_c1, 1
  %qh_n = select i1 %qn_n_c2, i64 %qn_q_c2, i64 %qn_q_c1
  %qn_r_md = sub i64 %qn_r_c1, %v_top
  %rh_n = select i1 %qn_n_c2, i64 %qn_r_md, i64 %qn_r_c1
  br label %refine_check

refine_check:
  %qh_in = phi i64 [%qh_s, %qhat_sat], [%qh_n, %qhat_normal]
  %rh_in = phi i64 [%rh_s, %qhat_sat], [%rh_n, %qhat_normal]
  %skip = phi i1 [%rh_ovf, %qhat_sat], [false, %qhat_normal]
  br i1 %skip, label %do_submul, label %refine_loop

refine_loop:
  %qh_r = phi i64 [%qh_in, %refine_check], [%qh_d, %refine_step]
  %rh_r = phi i64 [%rh_in, %refine_check], [%rh_a, %refine_step]
  %qh_rw = zext i64 %qh_r to i128
  %vt2w = zext i64 %v_top2 to i128
  %lhs = mul i128 %qh_rw, %vt2w
  %rh_rw = zext i64 %rh_r to i128
  %rh_rhi = shl i128 %rh_rw, 64
  %ut2w = zext i64 %ut2 to i128
  %rhs = or i128 %rh_rhi, %ut2w
  %need_ref = icmp ugt i128 %lhs, %rhs
  br i1 %need_ref, label %refine_step, label %do_submul

refine_step:
  %qh_d = sub i64 %qh_r, 1
  %rh_a = add i64 %rh_r, %v_top
  %rh_a_ovf = icmp ult i64 %rh_a, %rh_r
  br i1 %rh_a_ovf, label %do_submul, label %refine_loop

do_submul:
  %qh_use = phi i64 [%qh_in, %refine_check], [%qh_r, %refine_loop], [%qh_d, %refine_step]
  br label %sm_loop

sm_loop:
  %sm_i = phi i64 [0, %do_submul], [%sm_in, %sm_step]
  %sm_bw = phi i64 [0, %do_submul], [%sm_bn, %sm_step]
  %sm_done = icmp eq i64 %sm_i, %vn
  br i1 %sm_done, label %sm_finish, label %sm_step

sm_step:
  %sm_v_ptr = getelementptr i64, ptr %vshift, i64 %sm_i
  %sm_v = load i64, ptr %sm_v_ptr
  %sm_vw = zext i64 %sm_v to i128
  %sm_qhw = zext i64 %qh_use to i128
  %sm_p = mul i128 %sm_vw, %sm_qhw
  %sm_bww = zext i64 %sm_bw to i128
  %sm_pf = add i128 %sm_p, %sm_bww
  %sm_lo = trunc i128 %sm_pf to i64
  %sm_hiw = lshr i128 %sm_pf, 64
  %sm_hi = trunc i128 %sm_hiw to i64
  %sm_jpi = add i64 %j, %sm_i
  %sm_w_ptr = getelementptr i64, ptr %work, i64 %sm_jpi
  %sm_w_val = load i64, ptr %sm_w_ptr
  %sm_new = sub i64 %sm_w_val, %sm_lo
  store i64 %sm_new, ptr %sm_w_ptr
  %sm_wrap = icmp ult i64 %sm_w_val, %sm_lo
  %sm_w64 = zext i1 %sm_wrap to i64
  %sm_bn = add i64 %sm_hi, %sm_w64
  %sm_in = add i64 %sm_i, 1
  br label %sm_loop

sm_finish:
  %wt = load i64, ptr %ut_ptr
  %need_ab = icmp ult i64 %wt, %sm_bw
  %wt_n = sub i64 %wt, %sm_bw
  store i64 %wt_n, ptr %ut_ptr
  br i1 %need_ab, label %ab_init, label %m_after

ab_init:
  %qh_ab = sub i64 %qh_use, 1
  br label %ab_loop

ab_loop:
  %ab_i = phi i64 [0, %ab_init], [%ab_in, %ab_step]
  %ab_cy = phi i64 [0, %ab_init], [%ab_cn, %ab_step]
  %ab_done = icmp eq i64 %ab_i, %vn
  br i1 %ab_done, label %ab_finish, label %ab_step

ab_step:
  %ab_v_ptr = getelementptr i64, ptr %vshift, i64 %ab_i
  %ab_v = load i64, ptr %ab_v_ptr
  %ab_jpi = add i64 %j, %ab_i
  %ab_w_ptr = getelementptr i64, ptr %work, i64 %ab_jpi
  %ab_w_val = load i64, ptr %ab_w_ptr
  %ab_w_w = zext i64 %ab_w_val to i128
  %ab_v_w = zext i64 %ab_v to i128
  %ab_cy_w = zext i64 %ab_cy to i128
  %ab_s1 = add i128 %ab_w_w, %ab_v_w
  %ab_sf = add i128 %ab_s1, %ab_cy_w
  %ab_lo = trunc i128 %ab_sf to i64
  %ab_hiw = lshr i128 %ab_sf, 64
  %ab_cn = trunc i128 %ab_hiw to i64
  store i64 %ab_lo, ptr %ab_w_ptr
  %ab_in = add i64 %ab_i, 1
  br label %ab_loop

ab_finish:
  %wt_a = load i64, ptr %ut_ptr
  %wt_a_n = add i64 %wt_a, %ab_cy
  store i64 %wt_a_n, ptr %ut_ptr
  br label %m_after

m_after:
  %qh_final = phi i64 [%qh_use, %sm_finish], [%qh_ab, %ab_finish]
  %q_dst = getelementptr i64, ptr %qp, i64 %j
  store i64 %qh_final, ptr %q_dst
  %j_dec = sub i64 %j, 1
  br label %m_loop

  ; ===== Denormalize: rp[i] = (work[i] >> shift) | (work[i+1] << (64-shift)) =====
denorm_loop:
  %d_i = phi i64 [0, %s_finish], [0, %m_loop], [%d_in, %d_step]
  %d_done = icmp eq i64 %d_i, %vn
  br i1 %d_done, label %exit, label %d_step

d_step:
  %d_w_ptr = getelementptr i64, ptr %work, i64 %d_i
  %d_w = load i64, ptr %d_w_ptr
  %d_ip1 = add i64 %d_i, 1
  %d_w1_ptr = getelementptr i64, ptr %work, i64 %d_ip1
  %d_w1 = load i64, ptr %d_w1_ptr
  %d_lo = lshr i64 %d_w, %shift
  %d_hi = shl i64 %d_w1, %neg_shift
  %d_with = or i64 %d_lo, %d_hi
  %d_out = select i1 %has_shift, i64 %d_with, i64 %d_w
  %d_r_ptr = getelementptr i64, ptr %rp, i64 %d_i
  store i64 %d_out, ptr %d_r_ptr
  %d_in = add i64 %d_i, 1
  br label %denorm_loop

exit:
  ret void
}

attributes #0 = { nounwind "target-cpu"="skylake" "target-features"="+bmi2,+adx" }
'''


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    args = parser.parse_args()
    Path(args.output).parent.mkdir(parents=True, exist_ok=True)
    Path(args.output).write_text(IR, encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
