#!/usr/bin/env python3
import argparse
from pathlib import Path


HEADER = """#pragma once

// Generated by tools/fixint/gen_mpn.py. Do not edit by hand.

#define ZFACTOR_MPN_DECLARE_ONLY 1
#include "mpn_generic.h"
#undef ZFACTOR_MPN_DECLARE_ONLY

namespace zfactor::fixint::mpn {

template<int B>
__attribute__((always_inline)) inline uint8_t add_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_add_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline uint8_t add_block(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    return generic_add_block<B>(r, a, b, cy);
}

template<int B>
__attribute__((always_inline)) inline uint8_t sub_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_sub_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline uint8_t sub_block(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    return generic_sub_block<B>(r, a, b, bw);
}

template<int B>
__attribute__((always_inline)) inline limb_t addmul1_block(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
    return generic_addmul1_block<B>(r, a, scalar, cy);
}

template<int B>
__attribute__((always_inline)) inline limb_t submul1_block(limb_t* r, const limb_t* a, limb_t scalar, limb_t bw) {
    return generic_submul1_block<B>(r, a, scalar, bw);
}

template<int N>
__attribute__((always_inline)) inline bool sqr_small_asm(limb_t* r, const limb_t* a) {
    (void)r;
    (void)a;
    return false;
}

"""


FOOTER = """
template<int N, int B>
__attribute__((always_inline)) inline uint8_t add_chunked(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    if constexpr (N <= B) {
        return add_block<N>(r, a, b, cy);
    } else {
        cy = add_block<B>(r, a, b, cy);
        return add_chunked<N - B, B>(r + B, a + B, b + B, cy);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t add_chunked_first(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= B) {
        return add_block_first<N>(r, a, b);
    } else {
        uint8_t cy = add_block_first<B>(r, a, b);
        return add_chunked<N - B, B>(r + B, a + B, b + B, cy);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t sub_chunked(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    if constexpr (N <= B) {
        return sub_block<N>(r, a, b, bw);
    } else {
        bw = sub_block<B>(r, a, b, bw);
        return sub_chunked<N - B, B>(r + B, a + B, b + B, bw);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline uint8_t sub_chunked_first(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= B) {
        return sub_block_first<N>(r, a, b);
    } else {
        uint8_t bw = sub_block_first<B>(r, a, b);
        return sub_chunked<N - B, B>(r + B, a + B, b + B, bw);
    }
}

template<int N, int B>
__attribute__((always_inline)) inline limb_t addmul1_chunked(limb_t* r, const limb_t* a, limb_t b, limb_t cy) {
    if constexpr (N <= B) {
        return addmul1_block<N>(r, a, b, cy);
    } else {
        cy = addmul1_block<B>(r, a, b, cy);
        return addmul1_chunked<N - B, B>(r + B, a + B, b, cy);
    }
}

template<int N>
__attribute__((always_inline)) inline uint8_t add(limb_t* r, const limb_t* a, const limb_t* b) {
    return add_chunked_first<N, 8>(r, a, b);
}

template<int N>
__attribute__((always_inline)) inline uint8_t addc(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {
    return add_chunked<N, 8>(r, a, b, cy);
}

template<int N>
__attribute__((always_inline)) inline uint8_t sub(limb_t* r, const limb_t* a, const limb_t* b) {
    return sub_chunked_first<N, 8>(r, a, b);
}

template<int N>
__attribute__((always_inline)) inline uint8_t subc(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {
    return sub_chunked<N, 8>(r, a, b, bw);
}

template<int N>
__attribute__((always_inline)) inline limb_t addmul1(limb_t* r, const limb_t* a, limb_t b) {
    return addmul1_chunked<N, 8>(r, a, b, 0);
}

template<int N, int B>
__attribute__((always_inline)) inline limb_t submul1_chunked(limb_t* r, const limb_t* a, limb_t b, limb_t bw) {
    if constexpr (N <= B) {
        return submul1_block<N>(r, a, b, bw);
    } else {
        bw = submul1_block<B>(r, a, b, bw);
        return submul1_chunked<N - B, B>(r + B, a + B, b, bw);
    }
}

template<int N>
__attribute__((always_inline)) inline limb_t submul1(limb_t* r, const limb_t* a, limb_t b) {
    return submul1_chunked<N, 8>(r, a, b, 0);
}

} // namespace zfactor::fixint::mpn

#include "mpn_common.h"
"""


def add_first_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        if i == 0:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"addq {off}(%[b]), %[t]\\n\\t"')
        else:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"adcq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[cy], %[cy]\\n\\t"')
    lines.append('"negq %[cy]\\n\\t"')
    return "\n        ".join(lines)


def add_carry_asm(block: int) -> str:
    lines = [
        '"negq %[cy]\\n\\t"',
        '"movq 0(%[a]), %[t]\\n\\t"',
        '"adcq 0(%[b]), %[t]\\n\\t"',
        '"movq %[t], 0(%[r])\\n\\t"',
    ]
    for i in range(1, block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        lines.append(f'"adcq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[cy], %[cy]\\n\\t"')
    lines.append('"negq %[cy]\\n\\t"')
    return "\n        ".join(lines)


def sub_first_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        if i == 0:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"subq {off}(%[b]), %[t]\\n\\t"')
        else:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"sbbq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[bw], %[bw]\\n\\t"')
    lines.append('"negq %[bw]\\n\\t"')
    return "\n        ".join(lines)


def sub_carry_asm(block: int) -> str:
    lines = ['"negq %[bw]\\n\\t"']
    for i in range(block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        lines.append(f'"sbbq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[bw], %[bw]\\n\\t"')
    lines.append('"negq %[bw]\\n\\t"')
    return "\n        ".join(lines)


def add1_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        if i == 0:
            lines.append('"addq %[b], %[t]\\n\\t"')
        else:
            lines.append('"adcq $0, %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[cy], %[cy]\\n\\t"')
    lines.append('"negq %[cy]\\n\\t"')
    return "\n        ".join(lines)


def sub1_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        if i == 0:
            lines.append('"subq %[b], %[t]\\n\\t"')
        else:
            lines.append('"sbbq $0, %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[bw], %[bw]\\n\\t"')
    lines.append('"negq %[bw]\\n\\t"')
    return "\n        ".join(lines)


def lshift_small_asm(block: int) -> str:
    lines = []
    for i in range(block - 1, 0, -1):
        off = i * 8
        prev = (i - 1) * 8
        lines.append(f'"movq {prev}(%[a]), %[t0]\\n\\t"')
        lines.append(f'"movq {off}(%[a]), %[t1]\\n\\t"')
        lines.append(f'"shldq %%cl, %[t0], %[t1]\\n\\t"')
        lines.append(f'"movq %[t1], {off}(%[r])\\n\\t"')
    lines.append('"movq 0(%[a]), %[t0]\\n\\t"')
    lines.append('"shlq %%cl, %[t0]\\n\\t"')
    lines.append('"movq %[t0], 0(%[r])\\n\\t"')
    return "\n        ".join(lines)


def rshift_small_asm(block: int) -> str:
    lines = []
    for i in range(0, block - 1):
        off = i * 8
        nxt = (i + 1) * 8
        lines.append(f'"movq {off}(%[a]), %[t0]\\n\\t"')
        lines.append(f'"movq {nxt}(%[a]), %[t1]\\n\\t"')
        lines.append(f'"shrdq %%cl, %[t1], %[t0]\\n\\t"')
        lines.append(f'"movq %[t0], {off}(%[r])\\n\\t"')
    off = (block - 1) * 8
    lines.append(f'"movq {off}(%[a]), %[t0]\\n\\t"')
    lines.append('"shrq %%cl, %[t0]\\n\\t"')
    lines.append(f'"movq %[t0], {off}(%[r])\\n\\t"')
    return "\n        ".join(lines)


def tier1_addmul(block: int) -> str:
    lines = [
        '        __asm__ __volatile__(',
        '            "movq %[scalar], %%rdx\\n\\t"',
        '            "xorl %%eax, %%eax\\n\\t"',
    ]
    prev_hi = None
    for i in range(block):
        off = i * 8
        hi = "%[co]" if i == block - 1 else ("%[t1]" if i % 2 == 0 else "%[t2]")
        acc = "%[ci]" if i == 0 else prev_hi
        lines.append(f'            "mulx {off}(%[a]), %[t0], {hi}\\n\\t"')
        lines.append(f'            "adox {acc}, %[t0]\\n\\t"')
        lines.append(f'            "adcx {off}(%[r]), %[t0]\\n\\t"')
        lines.append(f'            "movq %[t0], {off}(%[r])\\n\\t"')
        prev_hi = hi
    lines.extend([
        '            "movq $0, %[t0]\\n\\t"',
        '            "adox %[t0], %[co]\\n\\t"',
        '            "adcx %[t0], %[co]\\n\\t"',
        '            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)',
        '            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)',
        '            : "rax", "rdx", "cc", "memory");',
    ])
    return "\n".join(lines)


def tier2_addmul(block: int) -> str:
    lines = [
        '        __asm__ __volatile__(',
        '            "movq %[scalar], %%rdx\\n\\t"',
    ]
    hi = "%[co]" if block == 1 else "%[t1]"
    lines.extend([
        f'            "mulx 0(%[a]), %[t0], {hi}\\n\\t"',
        '            "addq 0(%[r]), %[t0]\\n\\t"',
        f'            "adcq $0, {hi}\\n\\t"',
        '            "addq %[ci], %[t0]\\n\\t"',
        f'            "adcq $0, {hi}\\n\\t"',
        '            "movq %[t0], 0(%[r])\\n\\t"',
    ])
    prev_hi = hi
    for i in range(1, block):
        off = i * 8
        hi = "%[co]" if i == block - 1 else ("%[t1]" if i % 2 == 0 else "%[t2]")
        lines.extend([
            f'            "mulx {off}(%[a]), %[t0], {hi}\\n\\t"',
            f'            "addq {prev_hi}, %[t0]\\n\\t"',
            f'            "adcq {off}(%[r]), %[t0]\\n\\t"',
            f'            "movq %[t0], {off}(%[r])\\n\\t"',
            f'            "adcq $0, {hi}\\n\\t"',
        ])
        prev_hi = hi
    lines.extend([
        '            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)',
        '            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)',
        '            : "rdx", "cc", "memory");',
        "        return co;",
    ])
    return "\n".join(lines)


def emit_addmul1_block(block: int) -> str:
    return f"""
template<>
__attribute__((always_inline)) inline limb_t addmul1_block<{block}>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {{
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
{tier1_addmul(block).rstrip()}
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
{tier2_addmul(block)}
#else
    return generic_addmul1_block<{block}>(r, a, scalar, cy);
#endif
}}
"""


def tier2_submul(block: int) -> str:
    """BMI2-only ASM for submul1_block<B>: r[0..B-1] -= a[0..B-1] * scalar.
    Per-limb pattern: mulx + addq(prev_hi) + adcq(0) + subq(t0,r[i]) + adcq(0).
    """
    lines = [
        '        __asm__ __volatile__(',
        '            "movq %[scalar], %%rdx\\n\\t"',
    ]
    hi = "%[bo]" if block == 1 else "%[t1]"
    lines.extend([
        f'            "mulx 0(%[a]), %[t0], {hi}\\n\\t"',
        f'            "addq %[bi], %[t0]\\n\\t"',
        f'            "adcq $0, {hi}\\n\\t"',
        f'            "subq %[t0], 0(%[r])\\n\\t"',
        f'            "adcq $0, {hi}\\n\\t"',
    ])
    prev_hi = hi
    for i in range(1, block):
        off = i * 8
        hi = "%[bo]" if i == block - 1 else ("%[t1]" if i % 2 == 0 else "%[t2]")
        lines.extend([
            f'            "mulx {off}(%[a]), %[t0], {hi}\\n\\t"',
            f'            "addq {prev_hi}, %[t0]\\n\\t"',
            f'            "adcq $0, {hi}\\n\\t"',
            f'            "subq %[t0], {off}(%[r])\\n\\t"',
            f'            "adcq $0, {hi}\\n\\t"',
        ])
        prev_hi = hi
    lines.extend([
        '            : [bo] "=&r"(bo), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)',
        '            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [bi] "r"(bw)',
        '            : "rdx", "cc", "memory");',
        "        return bo;",
    ])
    return "\n".join(lines)


def tier1_submul(block: int) -> str:
    """BMI2+ADX ASM for submul1_block<B>.
    Uses GMP's complement trick: r -= a*s == r += ~(a*s) + 1.
    Two parallel carry chains: cf for the lo+~lo+r addition (via adcx),
    of for the hi accumulation (via adox).  The "borrow out" is the
    accumulated -hi value, which we negate at the end.
    """
    lines = [
        '        __asm__ __volatile__(',
        '            "movq %[scalar], %%rdx\\n\\t"',
        # Initialize: clear of (xor eax) and set cf=1 (stc, equivalent to "+1" for ~x+1 = -x)
        '            "xorl %%eax, %%eax\\n\\t"',
        '            "movq %[bi], %[bo]\\n\\t"',
        # Set cf for the initial +1: stc.  But we also need to subtract bi.
        # Easier path: bo accumulates -result_high; initialize bo = -bw_in (handled by neg).
        # Use neg to set CF = (bw_in != 0): if bw_in=0, neg sets cf=0; if bw_in=1, neg sets cf=1.
        '            "negq %[bo]\\n\\t"',
    ]
    # Loop body: per limb
    #   mulx a[i], t0, t1     ; t0:t1 = a[i]*scalar
    #   adox t1, bo           ; bo += t1 (using OF chain)
    #   not  t0               ; t0 = ~t0
    #   adcx r[i], t0         ; t0 += r[i] + CF (using CF chain)
    #   mov t0, r[i]
    # Need t1 != bo when block==1; use t2 for t1 in that case
    for i in range(block):
        off = i * 8
        hi_reg = "%[t1]" if i % 2 == 0 else "%[t2]"
        if block == 1:
            hi_reg = "%[t1]"
        lines.extend([
            f'            "mulx {off}(%[a]), %[t0], {hi_reg}\\n\\t"',
            f'            "adoxq {hi_reg}, %[bo]\\n\\t"',
            f'            "notq %[t0]\\n\\t"',
            f'            "adcxq {off}(%[r]), %[t0]\\n\\t"',
            f'            "movq %[t0], {off}(%[r])\\n\\t"',
        ])
    # Finalize: bo currently holds -result_high accumulated with both chains.
    # Need to fold the final cf and of into bo.
    #
    # After the loop:
    #   cf = 1 if no underflow on the last add, 0 if underflow
    #   of = 1 if of-chain on bo overflowed (rare)
    # bo holds the negated borrow with cf adjustment pending.
    # We want bw_out = -bo + (1 - cf) corrected for of.
    #
    # The simpler GMP idiom: at end,
    #   adox %[zero], %[bo]   ; absorb final of
    #   adc  $0, %[bo]        ; absorb final cf via the carry chain (becomes part of -bo)
    #   neg  %[bo]            ; bo = actual borrow_out
    lines.extend([
        '            "movq $0, %[t0]\\n\\t"',
        '            "adoxq %[t0], %[bo]\\n\\t"',
        '            "adcq  $0, %[bo]\\n\\t"',
        '            "negq  %[bo]\\n\\t"',
        '            : [bo] "+&r"(bo), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)',
        '            : [scalar] "r"(scalar), [r] "r"(r), [a] "r"(a), [bi] "r"(bw)',
        '            : "rax", "rdx", "cc", "memory");',
    ])
    return "\n".join(lines)


def emit_submul1_block(block: int) -> str:
    return f"""
template<>
__attribute__((always_inline)) inline limb_t submul1_block<{block}>(limb_t* r, const limb_t* a, limb_t scalar, limb_t bw) {{
#if defined(ZFACTOR_HAS_BMI2)
    limb_t bo = 0, t0 = 0, t1 = 0, t2 = 0;
{tier2_submul(block)}
#else
    return generic_submul1_block<{block}>(r, a, scalar, bw);
#endif
}}
"""


def emit_sqr_small_2() -> str:
    return """
template<>
__attribute__((always_inline)) inline bool sqr_small_asm<2>(limb_t* r, const limb_t* a) {
#if defined(ZFACTOR_HAS_BMI2)
    __asm__ __volatile__(
        "movq 0(%[a]), %%rdx\\n\\t"
        "mulx 8(%[a]), %%r8, %%r9\\n\\t"
        "mulx 0(%[a]), %%rax, %%r10\\n\\t"
        "movq 8(%[a]), %%rdx\\n\\t"
        "mulx 8(%[a]), %%r11, %%rbx\\n\\t"
        "xorq %%rcx, %%rcx\\n\\t"
        "addq %%r8, %%r8\\n\\t"
        "adcq %%r9, %%r9\\n\\t"
        "adcq $0, %%rcx\\n\\t"
        "addq %%r8, %%r10\\n\\t"
        "adcq %%r11, %%r9\\n\\t"
        "adcq %%rcx, %%rbx\\n\\t"
        "movq %%rax, 0(%[r])\\n\\t"
        "movq %%r10, 8(%[r])\\n\\t"
        "movq %%r9, 16(%[r])\\n\\t"
        "movq %%rbx, 24(%[r])\\n\\t"
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rbx", "rcx", "rdx", "r8", "r9", "r10", "r11", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}
"""


def emit_sqr_small_3() -> str:
    return """
template<>
__attribute__((always_inline)) inline bool sqr_small_asm<3>(limb_t* r, const limb_t* a) {
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    __asm__ __volatile__(
        "movq 0(%[a]), %%rdx\\n\\t"
        "mulx 8(%[a]), %%r10, %%r11\\n\\t"
        "mulx 16(%[a]), %%r8, %%r9\\n\\t"
        "addq %%r11, %%r8\\n\\t"
        "movq 8(%[a]), %%rdx\\n\\t"
        "mulx 16(%[a]), %%rax, %%r11\\n\\t"
        "adcq %%rax, %%r9\\n\\t"
        "adcq $0, %%r11\\n\\t"
        "xorq %%rcx, %%rcx\\n\\t"
        "movq 0(%[a]), %%rdx\\n\\t"
        "mulx 0(%[a]), %%rbx, %%rax\\n\\t"
        "movq %%rbx, 0(%[r])\\n\\t"
        "movq 8(%[a]), %%rdx\\n\\t"
        "mulx 8(%[a]), %%r14, %%r15\\n\\t"
        "movq 16(%[a]), %%rdx\\n\\t"
        "mulx 16(%[a]), %%rsi, %%rdx\\n\\t"
        "adcx %%r10, %%r10\\n\\t"
        "adcx %%r8, %%r8\\n\\t"
        "adcx %%r9, %%r9\\n\\t"
        "adcx %%r11, %%r11\\n\\t"
        "adox %%r10, %%rax\\n\\t"
        "adox %%r8, %%r14\\n\\t"
        "adox %%r9, %%r15\\n\\t"
        "adox %%r11, %%rsi\\n\\t"
        "adox %%rcx, %%rdx\\n\\t"
        "adcx %%rcx, %%rdx\\n\\t"
        "movq %%rax, 8(%[r])\\n\\t"
        "movq %%r14, 16(%[r])\\n\\t"
        "movq %%r15, 24(%[r])\\n\\t"
        "movq %%rsi, 32(%[r])\\n\\t"
        "movq %%rdx, 40(%[r])\\n\\t"
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rbx", "rcx", "rdx", "r8", "r9", "r10", "r11",
          "r14", "r15", "rsi", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}
"""


def sqr_diag_asm(off: int) -> list[str]:
    return [
        f'"movq {off}(%[a]), %%rax\\n\\t"',
        f'"mulq {off}(%[a])\\n\\t"',
        '"addq %%rax, %%r8\\n\\t"',
        '"adcq %%rdx, %%r9\\n\\t"',
        '"adcq $0, %%r10\\n\\t"',
    ]


def sqr_cross_asm(offa: int, offb: int) -> list[str]:
    return [
        f'"movq {offa}(%[a]), %%rax\\n\\t"',
        f'"mulq {offb}(%[a])\\n\\t"',
        '"xorq %%rcx, %%rcx\\n\\t"',
        '"addq %%rax, %%rax\\n\\t"',
        '"adcq %%rdx, %%rdx\\n\\t"',
        '"adcq $0, %%rcx\\n\\t"',
        '"addq %%rax, %%r8\\n\\t"',
        '"adcq %%rdx, %%r9\\n\\t"',
        '"adcq %%rcx, %%r10\\n\\t"',
    ]


def sqr_store_asm(off: int) -> list[str]:
    return [
        f'"movq %%r8, {off}(%[r])\\n\\t"',
        '"movq %%r9, %%r8\\n\\t"',
        '"movq %%r10, %%r9\\n\\t"',
        '"xorq %%r10, %%r10\\n\\t"',
    ]


def emit_sqr_small_comba(block: int) -> str:
    lines = [
        '"xorq %%r8, %%r8\\n\\t"',
        '"xorq %%r9, %%r9\\n\\t"',
        '"xorq %%r10, %%r10\\n\\t"',
    ]
    for col in range(2 * block - 1):
        low = max(0, col - (block - 1))
        high = min((col - 1) // 2, block - 1)
        for i in range(low, high + 1):
            j = col - i
            if i < j < block:
                lines.extend(sqr_cross_asm(i * 8, j * 8))
        if col % 2 == 0:
            i = col // 2
            if i < block:
                lines.extend(sqr_diag_asm(i * 8))
        if col + 1 < 2 * block - 1:
            lines.extend(sqr_store_asm(col * 8))
    final_off = (2 * block - 2) * 8
    lines.extend([
        f'"movq %%r8, {final_off}(%[r])\\n\\t"',
        f'"movq %%r9, {final_off + 8}(%[r])\\n\\t"',
    ])
    body = "\n        ".join(lines)
    return f"""
template<>
__attribute__((always_inline)) inline bool sqr_small_asm<{block}>(limb_t* r, const limb_t* a) {{
#if defined(__x86_64__)
    __asm__ __volatile__(
        {body}
        :
        : [r] "r"(r), [a] "r"(a)
        : "rax", "rcx", "rdx", "r8", "r9", "r10", "cc", "memory");
    return true;
#else
    (void)r;
    (void)a;
    return false;
#endif
}}
"""


def emit_add_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline uint8_t add_block_first<{block}>(limb_t* r, const limb_t* a, const limb_t* b) {{
    limb_t carry, t;
    __asm__ __volatile__(
        {add_first_asm(block)}
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}}

template<>
__attribute__((always_inline)) inline uint8_t add_block<{block}>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t cy) {{
    limb_t carry = cy;
    limb_t t;
    __asm__ __volatile__(
        {add_carry_asm(block)}
        : [cy] "+r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}}
"""
        )
    return "\n".join(parts)


def emit_add1_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline uint8_t add1<{block}>(limb_t* r, const limb_t* a, limb_t b) {{
    limb_t carry, t;
    __asm__ __volatile__(
        {add1_asm(block)}
        : [cy] "=r"(carry), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(carry);
}}
"""
        )
    return "\n".join(parts)


def emit_sub1_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline uint8_t sub1<{block}>(limb_t* r, const limb_t* a, limb_t b) {{
    limb_t borrow, t;
    __asm__ __volatile__(
        {sub1_asm(block)}
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}}
"""
        )
    return "\n".join(parts)


def emit_sub_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline uint8_t sub_block_first<{block}>(limb_t* r, const limb_t* a, const limb_t* b) {{
    limb_t borrow, t;
    __asm__ __volatile__(
        {sub_first_asm(block)}
        : [bw] "=r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}}

template<>
__attribute__((always_inline)) inline uint8_t sub_block<{block}>(limb_t* r, const limb_t* a, const limb_t* b, uint8_t bw) {{
    limb_t borrow = bw;
    limb_t t;
    __asm__ __volatile__(
        {sub_carry_asm(block)}
        : [bw] "+r"(borrow), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return static_cast<uint8_t>(borrow);
}}
"""
        )
    return "\n".join(parts)


def emit_shift_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline void lshift_small<{block}>(limb_t* r, const limb_t* a, unsigned bits) {{
    limb_t t0, t1;
    __asm__ __volatile__(
        {lshift_small_asm(block)}
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}}

template<>
__attribute__((always_inline)) inline void rshift_small<{block}>(limb_t* r, const limb_t* a, unsigned bits) {{
    limb_t t0, t1;
    __asm__ __volatile__(
        {rshift_small_asm(block)}
        : [t0] "=&r"(t0), [t1] "=&r"(t1)
        : [r] "r"(r), [a] "r"(a), [bits] "c"(bits)
        : "cc", "memory");
}}
"""
        )
    return "\n".join(parts)


def render() -> str:
    parts = [
        HEADER,
        emit_add_blocks(),
        emit_sub_blocks(),
        emit_add1_blocks(),
        emit_sub1_blocks(),
        emit_shift_blocks(),
    ]
    for block in range(1, 9):
        parts.append(emit_addmul1_block(block))
    for block in range(1, 9):
        parts.append(emit_submul1_block(block))
    parts.append(emit_sqr_small_2())
    parts.append(emit_sqr_small_3())
    parts.append(emit_sqr_small_comba(4))
    parts.append(FOOTER)
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--max-n", type=int, help="Deprecated no-op; generated dispatch is unbounded.")
    parser.add_argument("--arch", required=True, choices=["x86_64"])
    args = parser.parse_args()

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
