#!/usr/bin/env python3
"""Generate LLVM IR for CIOS Montgomery multiplication.

N=1-3: fully unrolled, emitted as separate functions (meant to be inlined).
N=4-8: loop-based single function parameterized by N.

Output: montmul_ir.ll → compiled by opt+llc into montmul_ir.o at build time.
"""
import argparse
from pathlib import Path

PREAMBLE = """\
; Generated by tools/fixint/gen_montmul_ir.py — do not edit.
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-pc-linux-gnu"

declare void @llvm.memset.p0.i64(ptr, i8, i64, i1)
"""


def usub_overflow_decls(max_n: int) -> str:
    """Declare llvm.usub.with.overflow at every width we use.

    The conditional subtract at the end of each montmul wants the borrow
    that comes out of the same subtraction operation — declaring the
    overloaded intrinsic explicitly makes LLVM fold the icmp+sub into
    one chain instead of computing them as two parallel chains.
    """
    lines = []
    for n in range(1, max_n + 1):
        nb = bits(n)
        lines.append(
            f"declare {{i{nb}, i1}} @llvm.usub.with.overflow.i{nb}(i{nb}, i{nb})"
        )
    return "\n".join(lines)


def bits(n: int) -> int:
    return 64 * n


def wide_bits(n: int) -> int:
    """Accumulator width: enough for N-limb * 1-limb + N-limb + carry = N+1 limbs."""
    return 64 * (n + 1)


def emit_cond_subtract(
    n: int,
    result_val: str,        # name of the i{nb} result value
    mod_val: str,           # name of the i{nb} mod value
    overflow_val: str,      # name of the i64 overflow value (0 / nonzero)
    result_limb_names: list,  # list of N i64 SSA names that compose result_val
                              # (used to feed the per-limb select); for the unrolled
                              # paths where we only have the i{nb}, pass None and
                              # we'll trunc/lshr it back into limbs.
) -> str:
    """Emit the final 'reduce mod' step.

    Two improvements over the naive `select i{nb}` pattern:

      1. Use llvm.usub.with.overflow.i{nb} so the trial subtract and the
         borrow flag come from the same instruction chain.  Stops LLVM from
         computing a separate i{nb} icmp+sbb chain in parallel.

      2. Split the i{nb} select into N independent i64 selects all
         conditioned on the same i1.  Sidesteps LLVM's lexicographic-tree
         lowering of `select i{nb}` for non-legal wide integer types,
         which on i192 collapses to three serial cmp+cmov groups
         (~10 cycles of cmov chain) instead of one parallel cmov set.
    """
    nb = bits(n)
    lines = []

    # Trial subtract: produces sub + borrow as one chain.
    lines.append(
        f"  %sub_pair = call {{i{nb}, i1}} "
        f"@llvm.usub.with.overflow.i{nb}(i{nb} {result_val}, i{nb} {mod_val})"
    )
    lines.append(f"  %sub = extractvalue {{i{nb}, i1}} %sub_pair, 0")
    lines.append(f"  %borrow = extractvalue {{i{nb}, i1}} %sub_pair, 1")
    lines.append(f"  %no_ov = icmp eq i64 {overflow_val}, 0")
    lines.append(f"  %need_undo = and i1 %no_ov, %borrow")

    # Split sub into N i64 limbs.  For N=1, %sub is already i64 — skip
    # the no-op trunc.
    if n == 1:
        sub_limbs = ["%sub"]
    else:
        for j in range(n):
            if j == 0:
                lines.append(f"  %sub_lo0 = trunc i{nb} %sub to i64")
            else:
                lines.append(f"  %sub_sh{j} = lshr i{nb} %sub, {j * 64}")
                lines.append(f"  %sub_lo{j} = trunc i{nb} %sub_sh{j} to i64")
        sub_limbs = [f"%sub_lo{j}" for j in range(n)]

    # Get the result limbs.  If caller passed them in directly we use them;
    # otherwise we trunc/lshr the i{nb} result value into limbs.
    if result_limb_names is None:
        if n == 1:
            result_limbs = [result_val]
        else:
            for j in range(n):
                if j == 0:
                    lines.append(f"  %res_lo0 = trunc i{nb} {result_val} to i64")
                else:
                    lines.append(f"  %res_sh{j} = lshr i{nb} {result_val}, {j * 64}")
                    lines.append(f"  %res_lo{j} = trunc i{nb} %res_sh{j} to i64")
            result_limbs = [f"%res_lo{j}" for j in range(n)]
    else:
        result_limbs = result_limb_names

    # N independent i64 selects, all on %need_undo — guarantees N parallel
    # cmovs at the asm level (one cycle each, no inter-limb dependency).
    for j in range(n):
        lines.append(
            f"  %out{j} = select i1 %need_undo, "
            f"i64 {result_limbs[j]}, i64 {sub_limbs[j]}"
        )

    # Store each limb to %r individually.
    for j in range(n):
        if j == 0:
            lines.append(f"  store i64 %out0, ptr %r, align 8")
        else:
            lines.append(f"  %r{j}_ptr = getelementptr i64, ptr %r, i64 {j}")
            lines.append(f"  store i64 %out{j}, ptr %r{j}_ptr, align 8")

    return "\n".join(lines)


def emit_unrolled_montmul(n: int) -> str:
    """Emit a fully unrolled montmul for a specific N (1-3).
    Uses wide integer arithmetic — LLVM legalizes to mulx/add/adc."""
    nb = bits(n)
    tb = bits(2 * n + 1)  # t buffer width
    lines = []

    fname = f"zfactor_montmul{n}"
    lines.append(f"define void @{fname}(ptr noalias %r, ptr noalias readonly %a_ptr,")
    lines.append(f"                     ptr noalias readonly %b_ptr, ptr noalias readonly %mod_ptr,")
    lines.append(f"                     i64 %inv) #{'1' if n <= 3 else '0'} {{")
    lines.append("entry:")

    # Load a as wide int
    lines.append(f"  %a = load i{nb}, ptr %a_ptr, align 8")
    lines.append(f"  %mod = load i{nb}, ptr %mod_ptr, align 8")

    # Load b limbs individually
    for i in range(n):
        if i == 0:
            lines.append(f"  %b{i} = load i64, ptr %b_ptr, align 8")
        else:
            lines.append(f"  %b{i}_ptr = getelementptr i64, ptr %b_ptr, i64 {i}")
            lines.append(f"  %b{i} = load i64, ptr %b{i}_ptr, align 8")

    # t = 0 (wide enough for 2N+1 limbs)
    t_cur = None  # will use literal 0 for first add
    for i in range(n):
        # === CIOS step i ===
        # Step 1: t += a * b[i]
        # Widen a and b[i] to tb bits, multiply, add to t
        lines.append(f"  %a_w{i} = zext i{nb} %a to i{tb}")
        lines.append(f"  %bi_w{i} = zext i64 %b{i} to i{tb}")
        lines.append(f"  %prod_a{i} = mul i{tb} %a_w{i}, %bi_w{i}")
        t_ref = f"%{t_cur}" if t_cur else "0"
        lines.append(f"  %t_add_a{i} = add i{tb} {t_ref}, %prod_a{i}")

        # Step 2: m = (t[0] & mask64) * inv
        lines.append(f"  %t0_{i} = trunc i{tb} %t_add_a{i} to i64")
        lines.append(f"  %m{i} = mul i64 %t0_{i}, %inv")

        # Step 3: t += mod * m
        lines.append(f"  %mod_w{i} = zext i{nb} %mod to i{tb}")
        lines.append(f"  %mi_w{i} = zext i64 %m{i} to i{tb}")
        lines.append(f"  %prod_m{i} = mul i{tb} %mod_w{i}, %mi_w{i}")
        lines.append(f"  %t_add_m{i} = add i{tb} %t_add_a{i}, %prod_m{i}")

        # Step 4: shift right by 64 (t[0] is zero by construction)
        lines.append(f"  %t_shr{i} = lshr i{tb} %t_add_m{i}, 64")
        t_cur = f"t_shr{i}"

    # Result is in the low N limbs of t_cur, overflow in limb N
    # Extract result (low nb bits) and overflow (bit nb)
    lines.append(f"  %result = trunc i{tb} %{t_cur} to i{nb}")
    lines.append(f"  %t_hi = lshr i{tb} %{t_cur}, {nb}")
    lines.append(f"  %overflow = trunc i{tb} %t_hi to i64")

    # Conditional subtract via the shared helper.
    lines.append(emit_cond_subtract(n, "%result", "%mod", "%overflow", None))
    lines.append("  ret void")
    lines.append("}")
    return "\n".join(lines)


def emit_looped_montmul(n: int) -> str:
    """Emit a loop-based montmul for a specific N (4-8).
    Uses a stack-allocated i64 array for t, and per-iteration addmul1 via
    widening multiply. Not inlined — called via extern C."""
    nb = bits(n)
    t_limbs = 2 * n + 1
    t_bytes = t_limbs * 8
    wb = wide_bits(n)  # N+1 limbs = 64*(N+1) bits

    fname = f"zfactor_montmul{n}"
    lines = []
    lines.append(f"define void @{fname}(ptr noalias %r, ptr noalias readonly %a_ptr,")
    lines.append(f"                     ptr noalias readonly %b_ptr, ptr noalias readonly %mod_ptr,")
    lines.append(f"                     i64 %inv) #0 {{")
    lines.append("entry:")

    # Load a, mod as wide ints
    lines.append(f"  %a = load i{nb}, ptr %a_ptr, align 8")
    lines.append(f"  %mod = load i{nb}, ptr %mod_ptr, align 8")

    # Allocate t on stack, zero-init
    lines.append(f"  %t = alloca [{t_limbs} x i64], align 8")
    lines.append(f"  call void @llvm.memset.p0.i64(ptr %t, i8 0, i64 {t_bytes}, i1 false)")

    lines.append(f"  br label %loop")
    lines.append("")
    lines.append(f"loop:")
    lines.append(f"  %i = phi i64 [0, %entry], [%i_next, %loop]")

    # Load b[i]
    lines.append(f"  %bi_ptr = getelementptr i64, ptr %b_ptr, i64 %i")
    lines.append(f"  %bi = load i64, ptr %bi_ptr, align 8")

    # Compute pointer to t[i]
    lines.append(f"  %ti_ptr = getelementptr i64, ptr %t, i64 %i")

    # Load t[i..i+N-1] as i{nb}, t[i+N] and t[i+N+1] as i64
    lines.append(f"  %t_lo = load i{nb}, ptr %ti_ptr, align 8")
    lines.append(f"  %ti_n_ptr = getelementptr i64, ptr %ti_ptr, i64 {n}")
    lines.append(f"  %t_n = load i64, ptr %ti_n_ptr, align 8")
    lines.append(f"  %ti_n1_ptr = getelementptr i64, ptr %ti_ptr, i64 {n + 1}")
    lines.append(f"  %t_n1 = load i64, ptr %ti_n1_ptr, align 8")

    # Assemble t_wide = t_n1:t_n:t_lo as i{wb+64} (N+2 limbs)
    wb2 = 64 * (n + 2)
    lines.append(f"  %t_lo_w = zext i{nb} %t_lo to i{wb2}")
    lines.append(f"  %t_n_w = zext i64 %t_n to i{wb2}")
    lines.append(f"  %t_n_sh = shl i{wb2} %t_n_w, {nb}")
    lines.append(f"  %t_n1_w = zext i64 %t_n1 to i{wb2}")
    lines.append(f"  %t_n1_sh = shl i{wb2} %t_n1_w, {nb + 64}")
    lines.append(f"  %t_wide = or i{wb2} %t_lo_w, %t_n_sh")
    lines.append(f"  %t_wide2 = or i{wb2} %t_wide, %t_n1_sh")

    # Step 1: t_wide += a * b[i]
    lines.append(f"  %a_w = zext i{nb} %a to i{wb2}")
    lines.append(f"  %bi_w = zext i64 %bi to i{wb2}")
    lines.append(f"  %prod_a = mul i{wb2} %a_w, %bi_w")
    lines.append(f"  %t_after_a = add i{wb2} %t_wide2, %prod_a")

    # Step 2: m = trunc(t_after_a) * inv
    lines.append(f"  %t0 = trunc i{wb2} %t_after_a to i64")
    lines.append(f"  %m = mul i64 %t0, %inv")

    # Step 3: t_wide += mod * m
    lines.append(f"  %mod_w = zext i{nb} %mod to i{wb2}")
    lines.append(f"  %m_w = zext i64 %m to i{wb2}")
    lines.append(f"  %prod_m = mul i{wb2} %mod_w, %m_w")
    lines.append(f"  %t_after_m = add i{wb2} %t_after_a, %prod_m")

    # Store back: extract limbs. t[i] should be 0 but store anyway for simplicity.
    # Store t[i..i+N+1] from t_after_m
    lines.append(f"  %out_lo = trunc i{wb2} %t_after_m to i{nb}")
    lines.append(f"  store i{nb} %out_lo, ptr %ti_ptr, align 8")
    lines.append(f"  %out_mid = lshr i{wb2} %t_after_m, {nb}")
    lines.append(f"  %out_n = trunc i{wb2} %out_mid to i64")
    lines.append(f"  store i64 %out_n, ptr %ti_n_ptr, align 8")
    lines.append(f"  %out_hi = lshr i{wb2} %t_after_m, {nb + 64}")
    lines.append(f"  %out_n1 = trunc i{wb2} %out_hi to i64")
    lines.append(f"  store i64 %out_n1, ptr %ti_n1_ptr, align 8")

    # Loop counter
    lines.append(f"  %i_next = add i64 %i, 1")
    lines.append(f"  %done = icmp eq i64 %i_next, {n}")
    lines.append(f"  br i1 %done, label %exit, label %loop")
    lines.append("")
    lines.append("exit:")

    # Load result: t[N..2N-1] and t[2N]
    lines.append(f"  %res_ptr = getelementptr i64, ptr %t, i64 {n}")
    lines.append(f"  %result = load i{nb}, ptr %res_ptr, align 8")
    lines.append(f"  %ov_ptr = getelementptr i64, ptr %t, i64 {2 * n}")
    lines.append(f"  %overflow = load i64, ptr %ov_ptr, align 8")

    # Conditional subtract via the shared helper.
    lines.append(emit_cond_subtract(n, "%result", "%mod", "%overflow", None))
    lines.append("  ret void")
    lines.append("}")
    return "\n".join(lines)


def emit_cios_montmul(n: int) -> str:
    """Emit a CIOS montmul for a specific N, fully unrolled.
    Uses negative inverse and addmul1 via i128 multiply-accumulate.
    LLVM sees the whole function and schedules across iteration boundaries."""
    nb = bits(n)
    lines = []

    fname = f"zfactor_montmul{n}"
    lines.append(f"define void @{fname}(ptr noalias %r, ptr noalias readonly %a_ptr,")
    lines.append(f"                     ptr noalias readonly %b_ptr, ptr noalias readonly %mod_ptr,")
    lines.append(f"                     i64 %inv) #0 {{")
    lines.append("entry:")

    # Load a[0..N-1], mod[0..N-1]
    for j in range(n):
        if j == 0:
            lines.append(f"  %a{j} = load i64, ptr %a_ptr, align 8")
            lines.append(f"  %mod{j} = load i64, ptr %mod_ptr, align 8")
        else:
            lines.append(f"  %a{j}_ptr = getelementptr i64, ptr %a_ptr, i64 {j}")
            lines.append(f"  %a{j} = load i64, ptr %a{j}_ptr, align 8")
            lines.append(f"  %mod{j}_ptr = getelementptr i64, ptr %mod_ptr, i64 {j}")
            lines.append(f"  %mod{j} = load i64, ptr %mod{j}_ptr, align 8")

    # t[0..2N] = 0, represented as individual SSA values
    # t_I_j = value of t[j] after CIOS iteration I
    # Initial: all zero
    t = {j: "0" for j in range(2 * n + 1)}

    for i in range(n):
        # Load b[i]
        if i == 0:
            lines.append(f"  %b{i} = load i64, ptr %b_ptr, align 8")
        else:
            lines.append(f"  %b{i}_ptr = getelementptr i64, ptr %b_ptr, i64 {i}")
            lines.append(f"  %b{i} = load i64, ptr %b{i}_ptr, align 8")

        # Phase 1: t[i..i+N-1] += a[0..N-1] * b[i]
        # Implemented as a chain of widening multiply-accumulates
        carry = "0"
        for j in range(n):
            pos = i + j
            # acc = a[j] * b[i] + t[pos] + carry
            a_w = f"%a{j}_w{i}_{j}"
            b_w = f"%b{i}_w{i}_{j}"
            lines.append(f"  {a_w} = zext i64 %a{j} to i128")
            lines.append(f"  {b_w} = zext i64 %b{i} to i128")
            prod = f"%prod_a{i}_{j}"
            lines.append(f"  {prod} = mul i128 {a_w}, {b_w}")
            # acc = prod + t[pos] + carry
            t_w = f"%t_w_a{i}_{j}"
            cy_w = f"%cy_w_a{i}_{j}"
            lines.append(f"  {t_w} = zext i64 {t[pos]} to i128")
            lines.append(f"  {cy_w} = zext i64 {carry} to i128")
            acc = f"%acc_a{i}_{j}"
            lines.append(f"  {acc}_1 = add i128 {prod}, {t_w}")
            lines.append(f"  {acc} = add i128 {acc}_1, {cy_w}")
            # t[pos] = lo(acc), carry = hi(acc)
            new_t = f"%t_{i}a_{pos}"
            new_cy = f"%cy_{i}a_{j}"
            lines.append(f"  {new_t} = trunc i128 {acc} to i64")
            shr = f"%shr_{i}a_{j}"
            lines.append(f"  {shr} = lshr i128 {acc}, 64")
            lines.append(f"  {new_cy} = trunc i128 {shr} to i64")
            t[pos] = new_t
            carry = new_cy

        # Propagate carry into t[i+N], t[i+N+1]
        pos_n = i + n
        acc_n = f"%prop_a{i}"
        lines.append(f"  {acc_n} = add i64 {t[pos_n]}, {carry}")
        ov = f"%ov_a{i}"
        lines.append(f"  {ov}_cmp = icmp ult i64 {acc_n}, {carry}")
        lines.append(f"  {ov} = zext i1 {ov}_cmp to i64")
        new_tn1 = f"%t_{i}a_{pos_n + 1}"
        lines.append(f"  {new_tn1} = add i64 {t[pos_n + 1]}, {ov}")
        t[pos_n] = acc_n
        t[pos_n + 1] = new_tn1

        # Phase 2: m = t[i] * inv (neg_inv)
        m_name = f"%m{i}"
        lines.append(f"  {m_name} = mul i64 {t[i]}, %inv")

        # Phase 3: t[i..i+N-1] += mod[0..N-1] * m
        carry = "0"
        for j in range(n):
            pos = i + j
            mod_w = f"%mod{j}_w{i}_{j}"
            m_w = f"%m{i}_w{i}_{j}"
            lines.append(f"  {mod_w} = zext i64 %mod{j} to i128")
            lines.append(f"  {m_w} = zext i64 {m_name} to i128")
            prod = f"%prod_m{i}_{j}"
            lines.append(f"  {prod} = mul i128 {mod_w}, {m_w}")
            t_w = f"%t_w_m{i}_{j}"
            cy_w = f"%cy_w_m{i}_{j}"
            lines.append(f"  {t_w} = zext i64 {t[pos]} to i128")
            lines.append(f"  {cy_w} = zext i64 {carry} to i128")
            acc = f"%acc_m{i}_{j}"
            lines.append(f"  {acc}_1 = add i128 {prod}, {t_w}")
            lines.append(f"  {acc} = add i128 {acc}_1, {cy_w}")
            new_t = f"%t_{i}m_{pos}"
            new_cy = f"%cy_{i}m_{j}"
            lines.append(f"  {new_t} = trunc i128 {acc} to i64")
            shr = f"%shr_{i}m_{j}"
            lines.append(f"  {shr} = lshr i128 {acc}, 64")
            lines.append(f"  {new_cy} = trunc i128 {shr} to i64")
            t[pos] = new_t
            carry = new_cy

        # Propagate carry
        pos_n = i + n
        acc_n = f"%prop_m{i}"
        lines.append(f"  {acc_n} = add i64 {t[pos_n]}, {carry}")
        ov = f"%ov_m{i}"
        lines.append(f"  {ov}_cmp = icmp ult i64 {acc_n}, {carry}")
        lines.append(f"  {ov} = zext i1 {ov}_cmp to i64")
        new_tn1 = f"%t_{i}m_{pos_n + 1}"
        lines.append(f"  {new_tn1} = add i64 {t[pos_n + 1]}, {ov}")
        t[pos_n] = acc_n
        t[pos_n + 1] = new_tn1

    # Result: t[N..2N-1], overflow = t[2N]
    #
    # We still need to assemble the i{nb} `result` and `mod_full` values
    # for the trial subtract — that's the only thing the usub.with.overflow
    # intrinsic operates on at width nb.  But we keep the per-limb i64
    # SSA names (`result_limbs`) so the per-limb selects in the helper
    # don't have to trunc/lshr them back out.
    result_limbs = [t[n + j] for j in range(n)]

    result_parts = []
    for j in range(n):
        w = f"%res_w{j}"
        lines.append(f"  {w} = zext i64 {t[n + j]} to i{nb}")
        if j > 0:
            sh = f"%res_sh{j}"
            lines.append(f"  {sh} = shl i{nb} {w}, {j * 64}")
            result_parts.append(sh)
        else:
            result_parts.append(w)
    cur = result_parts[0]
    for j in range(1, n):
        nxt = f"%res_or{j}"
        lines.append(f"  {nxt} = or i{nb} {cur}, {result_parts[j]}")
        cur = nxt
    result = cur

    mod_parts = []
    for j in range(n):
        w = f"%modf_w{j}"
        lines.append(f"  {w} = zext i64 %mod{j} to i{nb}")
        if j > 0:
            sh = f"%modf_sh{j}"
            lines.append(f"  {sh} = shl i{nb} {w}, {j * 64}")
            mod_parts.append(sh)
        else:
            mod_parts.append(w)
    cur_mod = mod_parts[0]
    for j in range(1, n):
        nxt = f"%modf_or{j}"
        lines.append(f"  {nxt} = or i{nb} {cur_mod}, {mod_parts[j]}")
        cur_mod = nxt
    mod_full = cur_mod

    overflow = t[2 * n]

    # Conditional subtract via the shared helper, passing the per-limb
    # SSA names so the per-limb selects don't re-extract them.
    lines.append(emit_cond_subtract(n, result, mod_full, overflow, result_limbs))
    lines.append("  ret void")
    lines.append("}")
    return "\n".join(lines)


def emit_cios_montmul_cpp(n: int) -> str:
    """Emit a fully-unrolled inline C++ montmul for a specific N (3-8).

    Mirrors emit_cios_montmul but emits C++ with __int128 and named locals
    instead of LLVM IR.  Each "t[pos]" slot is a separately-named uint64_t
    local, so clang can keep them in registers — the templated montmul_cios
    using `mp_limb_t t[2*N+1]` couldn't, because the array decays to stack.

    Marked [[gnu::always_inline]] so callers see it as a transparent body.
    """
    lines = []
    fname = f"montmul_inline_{n}"
    lines.append(
        f"[[gnu::always_inline]] inline void {fname}("
        f"std::uint64_t* __restrict r,"
        f" const std::uint64_t* __restrict a,"
        f" const std::uint64_t* __restrict b,"
        f" const std::uint64_t* __restrict mod,"
        f" std::uint64_t inv) {{"
    )
    lines.append("    using u128 = unsigned __int128;")

    # Load a, mod into named locals.
    for j in range(n):
        lines.append(f"    std::uint64_t a{j} = a[{j}];")
        lines.append(f"    std::uint64_t mod{j} = mod[{j}];")

    # All t slots start as 0; we use named locals so they stay in SSA/register.
    t = {j: "0" for j in range(2 * n + 1)}
    name_counter = [0]

    def fresh(prefix: str) -> str:
        name_counter[0] += 1
        return f"{prefix}_{name_counter[0]}"

    for i in range(n):
        lines.append(f"    // === CIOS iteration i={i} ===")
        lines.append(f"    std::uint64_t b{i} = b[{i}];")

        # Phase 1: t[i..i+N-1] += a * b[i]
        carry = "0"
        for j in range(n):
            pos = i + j
            acc = fresh("acc_a")
            lines.append(
                f"    u128 {acc} = (u128)a{j} * b{i} + {t[pos]} + {carry};"
            )
            new_t = fresh("t_a")
            lines.append(f"    std::uint64_t {new_t} = (std::uint64_t){acc};")
            new_cy = fresh("cy_a")
            lines.append(
                f"    std::uint64_t {new_cy} = (std::uint64_t)({acc} >> 64);"
            )
            t[pos] = new_t
            carry = new_cy

        # Propagate the final carry into t[i+N], t[i+N+1].
        pos_n = i + n
        new_tn = fresh("prop_a")
        lines.append(f"    std::uint64_t {new_tn} = {t[pos_n]} + {carry};")
        ov = fresh("ov_a")
        lines.append(
            f"    std::uint64_t {ov} = ({new_tn} < {carry}) ? 1 : 0;"
        )
        new_tn1 = fresh("t_a_high")
        lines.append(f"    std::uint64_t {new_tn1} = {t[pos_n + 1]} + {ov};")
        t[pos_n] = new_tn
        t[pos_n + 1] = new_tn1

        # Phase 2: m = t[i] * inv
        m_name = f"m{i}"
        lines.append(f"    std::uint64_t {m_name} = {t[i]} * inv;")

        # Phase 3: t[i..i+N-1] += mod * m
        carry = "0"
        for j in range(n):
            pos = i + j
            acc = fresh("acc_m")
            lines.append(
                f"    u128 {acc} = (u128)mod{j} * {m_name} + {t[pos]} + {carry};"
            )
            new_t = fresh("t_m")
            lines.append(f"    std::uint64_t {new_t} = (std::uint64_t){acc};")
            new_cy = fresh("cy_m")
            lines.append(
                f"    std::uint64_t {new_cy} = (std::uint64_t)({acc} >> 64);"
            )
            t[pos] = new_t
            carry = new_cy

        # Propagate the m-phase carry.
        pos_n = i + n
        new_tn = fresh("prop_m")
        lines.append(f"    std::uint64_t {new_tn} = {t[pos_n]} + {carry};")
        ov = fresh("ov_m")
        lines.append(
            f"    std::uint64_t {ov} = ({new_tn} < {carry}) ? 1 : 0;"
        )
        new_tn1 = fresh("t_m_high")
        lines.append(f"    std::uint64_t {new_tn1} = {t[pos_n + 1]} + {ov};")
        t[pos_n] = new_tn
        t[pos_n + 1] = new_tn1

    # === Conditional reduce ===
    # Result is t[N..2N-1]; overflow is t[2N].
    overflow = t[2 * n]
    result_locals = [t[n + j] for j in range(n)]

    lines.append(f"    // === Conditional reduce ===")
    # Trial subtract limb by limb with explicit borrow chain.
    lines.append(f"    std::uint64_t sub_borrow = 0;")
    sub_locals = []
    for j in range(n):
        sub_v = fresh("sub")
        lines.append(
            f"    std::uint64_t {sub_v};"
        )
        # Use __builtin_sub_overflow chained: sub_v = result - mod - sub_borrow
        lines.append(
            f"    {{"
        )
        lines.append(
            f"        unsigned long long _diff;"
        )
        lines.append(
            f"        unsigned long long _b1 = "
            f"__builtin_sub_overflow({result_locals[j]}, mod{j}, &_diff);"
        )
        lines.append(
            f"        unsigned long long _b2 = "
            f"__builtin_sub_overflow(_diff, sub_borrow, &_diff);"
        )
        lines.append(f"        {sub_v} = _diff;")
        lines.append(f"        sub_borrow = _b1 | _b2;")
        lines.append(f"    }}")
        sub_locals.append(sub_v)

    # need_undo = (overflow == 0) && sub_borrow
    # Equivalently: use the sub if (overflow != 0) || !sub_borrow
    lines.append(
        f"    bool use_sub = ({overflow} != 0) | (sub_borrow == 0);"
    )

    # Per-limb selects via ternary — clang lowers each as a parallel cmov on
    # the same flag.
    for j in range(n):
        lines.append(
            f"    r[{j}] = use_sub ? {sub_locals[j]} : {result_locals[j]};"
        )

    lines.append("}")
    return "\n".join(lines)


def render_cpp(max_n: int) -> str:
    parts = []
    parts.append("// Generated by tools/fixint/gen_montmul_ir.py — do not edit.")
    parts.append("// Inline C++ CIOS montmul kernels for N=3..8.")
    parts.append("//")
    parts.append("// Each function is fully unrolled with named locals so clang can")
    parts.append("// keep the t[] state in SSA/registers (vs the stack-allocated")
    parts.append("// montmul_cios template).  Marked always_inline so the body")
    parts.append("// inlines into the calling montmul<N>() dispatch and pays no")
    parts.append("// function-call overhead.")
    parts.append("#pragma once")
    parts.append("")
    parts.append("#include <cstdint>")
    parts.append("")
    parts.append("namespace zfactor::fixint {")
    parts.append("")
    for n in range(3, max_n + 1):
        parts.append(emit_cios_montmul_cpp(n))
        parts.append("")
    parts.append("}  // namespace zfactor::fixint")
    return "\n".join(parts) + "\n"


def render(max_n: int, cpu: str = "skylake") -> str:
    parts = [PREAMBLE]
    parts.append(usub_overflow_decls(max_n))
    parts.append("")

    # N=1-2: positive-inverse unrolled (fast for small N)
    for n in range(1, min(max_n, 2) + 1):
        parts.append(emit_unrolled_montmul(n))
        parts.append("")

    # N=3+: CIOS unrolled (better register pressure for larger N)
    for n in range(3, max_n + 1):
        parts.append(emit_cios_montmul(n))
        parts.append("")

    parts.append(f'attributes #0 = {{ nounwind "target-cpu"="{cpu}" "target-features"="+bmi2,+adx" }}')
    parts.append(f'attributes #1 = {{ nounwind alwaysinline "target-cpu"="{cpu}" "target-features"="+bmi2,+adx" }}')
    return "\n".join(parts) + "\n"


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=False,
                        help="Path to write the LLVM IR file.")
    parser.add_argument("--output-cpp", required=False,
                        help="Path to write the inline C++ header.")
    parser.add_argument("--max-n", type=int, default=8)
    args = parser.parse_args()

    if args.output:
        output = Path(args.output)
        output.parent.mkdir(parents=True, exist_ok=True)
        output.write_text(render(args.max_n), encoding="utf-8", newline="\n")
    if args.output_cpp:
        output_cpp = Path(args.output_cpp)
        output_cpp.parent.mkdir(parents=True, exist_ok=True)
        output_cpp.write_text(render_cpp(args.max_n), encoding="utf-8", newline="\n")
    if not args.output and not args.output_cpp:
        parser.error("must specify --output or --output-cpp (or both)")


if __name__ == "__main__":
    main()
