#!/usr/bin/env python3
import argparse
from pathlib import Path


HEADER = """#pragma once

// Generated by scripts/gen_mpn.py. Do not edit by hand.

#define ZFACTOR_MPN_DECLARE_ONLY 1
#include "mpn_generic.h"
#undef ZFACTOR_MPN_DECLARE_ONLY

namespace zfactor::mpn {

template<int B>
__attribute__((always_inline)) inline limb_t add_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_add_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline limb_t add_block(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {
    return generic_add_block<B>(r, a, b, cy);
}

template<int B>
__attribute__((always_inline)) inline limb_t sub_block_first(limb_t* r, const limb_t* a, const limb_t* b) {
    return generic_sub_block<B>(r, a, b, 0);
}

template<int B>
__attribute__((always_inline)) inline limb_t sub_block(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {
    return generic_sub_block<B>(r, a, b, bw);
}

template<int B>
__attribute__((always_inline)) inline limb_t addmul1_block(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {
    return generic_addmul1_block<B>(r, a, scalar, cy);
}

"""


FOOTER = """
template<int N>
__attribute__((always_inline)) inline limb_t add(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= 8) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t cy = 0;
        if constexpr (full != 0) {
            cy = add_block_first<8>(r, a, b);
            for (int j = 1; j < full; ++j)
                cy = add_block<8>(r + j * 8, a + j * 8, b + j * 8, cy);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                cy = add_block_first<rem>(r, a, b);
            else
                cy = add_block<rem>(r + full * 8, a + full * 8, b + full * 8, cy);
        }
        return cy;
    } else if constexpr (N <= @@MAX_N@@) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t cy = add_block_first<8>(r, a, b);
        for (int j = 1; j < full; ++j)
            cy = add_block<8>(r + j * 8, a + j * 8, b + j * 8, cy);
        if constexpr (rem != 0)
            cy = add_block<rem>(r + full * 8, a + full * 8, b + full * 8, cy);
        return cy;
    } else {
        return generic_add<N>(r, a, b);
    }
}

template<int N>
__attribute__((always_inline)) inline limb_t sub(limb_t* r, const limb_t* a, const limb_t* b) {
    if constexpr (N <= 8) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t bw = 0;
        if constexpr (full != 0) {
            bw = sub_block_first<8>(r, a, b);
            for (int j = 1; j < full; ++j)
                bw = sub_block<8>(r + j * 8, a + j * 8, b + j * 8, bw);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                bw = sub_block_first<rem>(r, a, b);
            else
                bw = sub_block<rem>(r + full * 8, a + full * 8, b + full * 8, bw);
        }
        return bw;
    } else if constexpr (N <= @@MAX_N@@) {
        constexpr int full = N / 8;
        constexpr int rem = N % 8;
        limb_t bw = sub_block_first<8>(r, a, b);
        for (int j = 1; j < full; ++j)
            bw = sub_block<8>(r + j * 8, a + j * 8, b + j * 8, bw);
        if constexpr (rem != 0)
            bw = sub_block<rem>(r + full * 8, a + full * 8, b + full * 8, bw);
        return bw;
    } else {
        return generic_sub<N>(r, a, b);
    }
}

template<int N>
__attribute__((always_inline)) inline limb_t addmul1(limb_t* r, const limb_t* a, limb_t b) {
    if constexpr (N <= 4) {
        constexpr int full = N / 4;
        constexpr int rem = N % 4;
        limb_t cy = 0;
        if constexpr (full != 0) {
            cy = addmul1_block<4>(r, a, b, cy);
            for (int j = 1; j < full; ++j)
                cy = addmul1_block<4>(r + j * 4, a + j * 4, b, cy);
        }
        if constexpr (rem != 0) {
            if constexpr (full == 0)
                cy = addmul1_block<rem>(r, a, b, cy);
            else
                cy = addmul1_block<rem>(r + full * 4, a + full * 4, b, cy);
        }
        return cy;
    } else if constexpr (N <= @@MAX_N@@) {
        constexpr int full = N / 4;
        constexpr int rem = N % 4;
        limb_t cy = addmul1_block<4>(r, a, b, 0);
        for (int j = 1; j < full; ++j)
            cy = addmul1_block<4>(r + j * 4, a + j * 4, b, cy);
        if constexpr (rem != 0)
            cy = addmul1_block<rem>(r + full * 4, a + full * 4, b, cy);
        return cy;
    } else {
        return generic_addmul1<N>(r, a, b);
    }
}

} // namespace zfactor::mpn

#include "mpn_common.h"
"""


def add_first_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        if i == 0:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"addq {off}(%[b]), %[t]\\n\\t"')
        else:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"adcq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[cy], %[cy]\\n\\t"')
    lines.append('"negq %[cy]\\n\\t"')
    return "\n        ".join(lines)


def add_carry_asm(block: int) -> str:
    lines = [
        '"negq %[cy]\\n\\t"',
        '"movq 0(%[a]), %[t]\\n\\t"',
        '"adcq 0(%[b]), %[t]\\n\\t"',
        '"movq %[t], 0(%[r])\\n\\t"',
    ]
    for i in range(1, block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        lines.append(f'"adcq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[cy], %[cy]\\n\\t"')
    lines.append('"negq %[cy]\\n\\t"')
    return "\n        ".join(lines)


def sub_first_asm(block: int) -> str:
    lines = []
    for i in range(block):
        off = i * 8
        if i == 0:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"subq {off}(%[b]), %[t]\\n\\t"')
        else:
            lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
            lines.append(f'"sbbq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[bw], %[bw]\\n\\t"')
    lines.append('"negq %[bw]\\n\\t"')
    return "\n        ".join(lines)


def sub_carry_asm(block: int) -> str:
    lines = ['"negq %[bw]\\n\\t"']
    for i in range(block):
        off = i * 8
        lines.append(f'"movq {off}(%[a]), %[t]\\n\\t"')
        lines.append(f'"sbbq {off}(%[b]), %[t]\\n\\t"')
        lines.append(f'"movq %[t], {off}(%[r])\\n\\t"')
    lines.append('"sbbq %[bw], %[bw]\\n\\t"')
    lines.append('"negq %[bw]\\n\\t"')
    return "\n        ".join(lines)


def tier1_addmul(block: int) -> str:
    if block == 1:
        body = """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "xorl %%eax, %%eax\\n\\t"
            "mulx 0(%[a]), %[t0], %[co]\\n\\t"
            "adox %[ci], %[t0]\\n\\t"
            "adcx 0(%[r]), %[t0]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "movq $0, %[t0]\\n\\t"
            "adox %[t0], %[co]\\n\\t"
            "adcx %[t0], %[co]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
"""
    elif block == 2:
        body = """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "xorl %%eax, %%eax\\n\\t"
            "mulx 0(%[a]), %[t0], %[t1]\\n\\t"
            "adox %[ci], %[t0]\\n\\t"
            "adcx 0(%[r]), %[t0]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[co]\\n\\t"
            "adox %[t1], %[t0]\\n\\t"
            "adcx 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "movq $0, %[t0]\\n\\t"
            "adox %[t0], %[co]\\n\\t"
            "adcx %[t0], %[co]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
"""
    elif block == 3:
        body = """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "xorl %%eax, %%eax\\n\\t"
            "mulx 0(%[a]), %[t0], %[t1]\\n\\t"
            "adox %[ci], %[t0]\\n\\t"
            "adcx 0(%[r]), %[t0]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[t2]\\n\\t"
            "adox %[t1], %[t0]\\n\\t"
            "adcx 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "mulx 16(%[a]), %[t0], %[co]\\n\\t"
            "adox %[t2], %[t0]\\n\\t"
            "adcx 16(%[r]), %[t0]\\n\\t"
            "movq %[t0], 16(%[r])\\n\\t"
            "movq $0, %[t0]\\n\\t"
            "adox %[t0], %[co]\\n\\t"
            "adcx %[t0], %[co]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
"""
    else:
        body = """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "xorl %%eax, %%eax\\n\\t"
            "mulx 0(%[a]), %[t0], %[t1]\\n\\t"
            "adox %[ci], %[t0]\\n\\t"
            "adcx 0(%[r]), %[t0]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[t2]\\n\\t"
            "adox %[t1], %[t0]\\n\\t"
            "adcx 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "mulx 16(%[a]), %[t0], %[t1]\\n\\t"
            "adox %[t2], %[t0]\\n\\t"
            "adcx 16(%[r]), %[t0]\\n\\t"
            "movq %[t0], 16(%[r])\\n\\t"
            "mulx 24(%[a]), %[t0], %[co]\\n\\t"
            "adox %[t1], %[t0]\\n\\t"
            "adcx 24(%[r]), %[t0]\\n\\t"
            "movq %[t0], 24(%[r])\\n\\t"
            "movq $0, %[t0]\\n\\t"
            "adox %[t0], %[co]\\n\\t"
            "adcx %[t0], %[co]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rax", "rdx", "cc", "memory");
"""
    return body


def tier2_addmul(block: int) -> str:
    if block == 1:
        return """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "mulx 0(%[a]), %[t0], %[co]\\n\\t"
            "adcq 0(%[r]), %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "addq %[ci], %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return co;
"""
    if block == 2:
        return """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "mulx 0(%[a]), %[t0], %[co]\\n\\t"
            "adcq 0(%[r]), %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "addq %[ci], %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[t1]\\n\\t"
            "addq %[co], %[t0]\\n\\t"
            "adcq 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "adcq $0, %[t1]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t1;
"""
    if block == 3:
        return """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "mulx 0(%[a]), %[t0], %[co]\\n\\t"
            "adcq 0(%[r]), %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "addq %[ci], %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[t1]\\n\\t"
            "addq %[co], %[t0]\\n\\t"
            "adcq 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "adcq $0, %[t1]\\n\\t"
            "mulx 16(%[a]), %[t0], %[t2]\\n\\t"
            "addq %[t1], %[t0]\\n\\t"
            "adcq 16(%[r]), %[t0]\\n\\t"
            "movq %[t0], 16(%[r])\\n\\t"
            "adcq $0, %[t2]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t2;
"""
    return """
        __asm__ __volatile__(
            "movq %[scalar], %%rdx\\n\\t"
            "mulx 0(%[a]), %[t0], %[co]\\n\\t"
            "adcq 0(%[r]), %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "addq %[ci], %[t0]\\n\\t"
            "adcq $0, %[co]\\n\\t"
            "movq %[t0], 0(%[r])\\n\\t"
            "mulx 8(%[a]), %[t0], %[t1]\\n\\t"
            "addq %[co], %[t0]\\n\\t"
            "adcq 8(%[r]), %[t0]\\n\\t"
            "movq %[t0], 8(%[r])\\n\\t"
            "adcq $0, %[t1]\\n\\t"
            "mulx 16(%[a]), %[t0], %[t2]\\n\\t"
            "addq %[t1], %[t0]\\n\\t"
            "adcq 16(%[r]), %[t0]\\n\\t"
            "movq %[t0], 16(%[r])\\n\\t"
            "adcq $0, %[t2]\\n\\t"
            "mulx 24(%[a]), %[t0], %[t1]\\n\\t"
            "addq %[t2], %[t0]\\n\\t"
            "adcq 24(%[r]), %[t0]\\n\\t"
            "movq %[t0], 24(%[r])\\n\\t"
            "adcq $0, %[t1]\\n\\t"
            : [co] "=&r"(co), [t0] "=&r"(t0), [t1] "=&r"(t1), [t2] "=&r"(t2)
            : [r] "r"(r), [a] "r"(a), [scalar] "r"(scalar), [ci] "r"(cy)
            : "rdx", "cc", "memory");
        return t1;
"""


def emit_addmul1_block(block: int) -> str:
    return f"""
template<>
__attribute__((always_inline)) inline limb_t addmul1_block<{block}>(limb_t* r, const limb_t* a, limb_t scalar, limb_t cy) {{
#if defined(ZFACTOR_HAS_BMI2) && defined(ZFACTOR_HAS_ADX)
    limb_t co, t0, t1 = 0, t2 = 0;
{tier1_addmul(block).rstrip()}
    return co;
#elif defined(ZFACTOR_HAS_BMI2)
    limb_t co = 0, t0 = 0, t1 = 0, t2 = 0;
{tier2_addmul(block)}
#else
    return generic_addmul1_block<{block}>(r, a, scalar, cy);
#endif
}}
"""


def emit_add_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline limb_t add_block_first<{block}>(limb_t* r, const limb_t* a, const limb_t* b) {{
    limb_t cy, t;
    __asm__ __volatile__(
        {add_first_asm(block)}
        : [cy] "=r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}}

template<>
__attribute__((always_inline)) inline limb_t add_block<{block}>(limb_t* r, const limb_t* a, const limb_t* b, limb_t cy) {{
    limb_t t;
    __asm__ __volatile__(
        {add_carry_asm(block)}
        : [cy] "+r"(cy), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return cy;
}}
"""
        )
    return "\n".join(parts)


def emit_sub_blocks() -> str:
    parts = []
    for block in range(1, 9):
        parts.append(
            f"""
template<>
__attribute__((always_inline)) inline limb_t sub_block_first<{block}>(limb_t* r, const limb_t* a, const limb_t* b) {{
    limb_t bw, t;
    __asm__ __volatile__(
        {sub_first_asm(block)}
        : [bw] "=r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}}

template<>
__attribute__((always_inline)) inline limb_t sub_block<{block}>(limb_t* r, const limb_t* a, const limb_t* b, limb_t bw) {{
    limb_t t;
    __asm__ __volatile__(
        {sub_carry_asm(block)}
        : [bw] "+r"(bw), [t] "=&r"(t)
        : [r] "r"(r), [a] "r"(a), [b] "r"(b)
        : "cc", "memory");
    return bw;
}}
"""
        )
    return "\n".join(parts)


def render(max_n: int) -> str:
    parts = [HEADER, emit_add_blocks(), emit_sub_blocks()]
    for block in range(1, 5):
        parts.append(emit_addmul1_block(block))
    parts.append(FOOTER.replace("@@MAX_N@@", str(max_n)))
    return "".join(parts)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--output", required=True)
    parser.add_argument("--max-n", required=True, type=int)
    parser.add_argument("--arch", required=True, choices=["x86_64"])
    args = parser.parse_args()

    if args.max_n < 1:
        raise SystemExit("--max-n must be >= 1")

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(render(args.max_n), encoding="utf-8", newline="\n")


if __name__ == "__main__":
    main()
