// Benchmark: FFT polynomial stage 2 vs BSGS stage 2.
// Uses exact B1/B2 from GMP-ECM table matched to known factor size.
// Outputs per-curve stage 2 time for scaling analysis.
#include "zfactor/eecm/curve_setup.h"
#include "zfactor/eecm/scalar_mult.h"
#include "zfactor/eecm/schedule_generated.h"
#include "zfactor/eecm/stage2.h"
#include "zfactor/eecm/stage2_poly.h"
#include "zfactor/eecm.h"
#include "zfactor/sieve.h"
#include <zint/zint.hpp>
#include <cstdio>
#include <cstdint>
#include <cstring>
#include <chrono>

using namespace zfactor::fixint;
using namespace zfactor::ecm;
using Clock = std::chrono::steady_clock;

// ── GMP-ECM optimal B1/B2 for known factor digit count ──
struct ECMParams { int digits; uint64_t B1; uint64_t B2; };
static const ECMParams GMPECM[] = {
    {20,    11000,       1900000},
    {25,    50000,      13000000},
    {30,   250000,     130000000},
    {35,  1000000,    1000000000},
    {40,  3000000,    5700000000},
    {45, 11000000,   35000000000},
    {50, 43000000,  240000000000},
    {55,110000000,  780000000000},
    {60,260000000, 3200000000000},
};

// ── Test semiprimes (generated by tools/gen_test_semiprimes.py) ──
// Each is p*q where p,q are half-bit primes.
struct TestCase {
    int bits;          // total semiprime bits
    int factor_digits; // digits of each factor (= bits/2 * log10(2))
    int N;             // UInt<N>
    uint64_t limbs[4];
    uint64_t B1, B2;   // from GMP-ECM table
};

static const TestCase CASES[] = {
    // 60bit: 30bit factors ≈ 9 digits → use 20-digit row (closest safe)
    { 60,  9, 1, {0x040005E180AB6CABULL}, 11000, 1900000},
    // 80bit: 40bit factors ≈ 12 digits → 20-digit row
    { 80, 12, 2, {0x0017920000AD539BULL, 0x0000000000004000ULL}, 11000, 1900000},
    // 100bit: 50bit factors ≈ 15 digits → 20-digit row
    {100, 15, 2, {0x6078000000C62ECBULL, 0x0000000400000000ULL}, 11000, 1900000},
    // 120bit: 60bit factors ≈ 18 digits → 20-digit row
    {120, 18, 2, {0x8000000000B05D4FULL, 0x004000000000017BULL}, 11000, 1900000},
    // 140bit: 70bit factors ≈ 21 digits → 25-digit row
    {140, 21, 3, {0x0000000000B883A5ULL, 0x000000000005F8C0ULL, 0x0000000000000400ULL}, 50000, 13000000},
    // 160bit: 80bit factors ≈ 24 digits → 25-digit row
    {160, 24, 3, {0x0000000000B56CF9ULL, 0x0000000017BD0000ULL, 0x0000000040000000ULL}, 50000, 13000000},
    // 180bit: 90bit factors ≈ 27 digits → 30-digit row
    {180, 27, 3, {0x0000000000B2DD57ULL, 0x0000005EC0000000ULL, 0x0004000000000000ULL}, 250000, 130000000},
    // 200bit: 100bit factors ≈ 30 digits → 30-digit row
    {200, 30, 4, {0x0000000000B1D9E9ULL, 0x00017AD000000000ULL, 0x0000000000000000ULL, 0x0000000000000040ULL}, 250000, 130000000},
};
static const int NCASES = sizeof(CASES) / sizeof(CASES[0]);

template<int N, typename S2Func>
double run_one(UInt<N> n, uint64_t B1, uint64_t B2, uint64_t curve_k,
               S2Func s2func, bool& found, bool& stage1_hit) {
    MontCtx<N> ctx;
    ctx.init(n);

    auto cs = setup_curve<N>(curve_k, ctx);
    if (cs.factor_found) { found = true; stage1_hit = true; return 0; }

    const auto& chain = get_stage1_chain(B1);
    std::vector<EdPoint<N>> precomp, precomp_neg;
    build_wnaf_precomp<N>(precomp, precomp_neg, cs.P0, chain.w, cs.curve, ctx);
    auto Q = scalar_mult_wnaf<N>(chain.wnaf, precomp, precomp_neg, cs.curve, ctx);

    auto m = mont(ctx);
    auto X_plain = m.drop(Q.X);
    if (X_plain.is_zero()) X_plain = ctx.mod;
    auto g = gcd<N>(X_plain, ctx.mod);
    if (!g.is_zero() && mpn::cmp<N>(g.d, UInt<N>(1).d) > 0
                     && mpn::cmp<N>(g.d, ctx.mod.d) < 0) {
        found = true; stage1_hit = true; return 0;
    }

    auto t0 = Clock::now();
    auto s2 = s2func(Q, cs.curve, B1, B2, ctx);
    auto t1 = Clock::now();
    if (s2.factor_found) found = true;
    return std::chrono::duration<double, std::milli>(t1 - t0).count();
}

template<int N>
void bench(const TestCase& tc, int ncurves) {
    UInt<N> n{};
    std::memcpy(n.d, tc.limbs, N * 8);

    double sum_bsgs = 0, sum_fft = 0;
    int s2_bsgs = 0, s2_fft = 0;
    int hit_bsgs = 0, hit_fft = 0;
    int s1_hit = 0;

    for (int k = 2; k < 2 + ncurves; ++k) {
        bool fb = false, ff = false;
        bool s1b = false, s1f = false;
        double mb = run_one<N>(n, tc.B1, tc.B2, k, ecm_stage2<N>, fb, s1b);
        double mf = run_one<N>(n, tc.B1, tc.B2, k, ecm_stage2_poly<N>, ff, s1f);
        if (s1b) { s1_hit++; continue; }  // skip stage-1 hits for stage-2 timing
        sum_bsgs += mb; s2_bsgs++;
        sum_fft += mf; s2_fft++;
        if (fb) hit_bsgs++;
        if (ff) hit_fft++;
    }

    double avg_b = s2_bsgs ? sum_bsgs / s2_bsgs : 0;
    double avg_f = s2_fft ? sum_fft / s2_fft : 0;

    std::printf("%3dbit N=%d  B1=%-8lu B2=%-12lu range=%8.1fM  "
                "BSGS %7.2fms/c (%2d/%2d)  FFT %7.2fms/c (%2d/%2d)",
                tc.bits, N, tc.B1, tc.B2, (tc.B2 - tc.B1) / 1e6,
                avg_b, hit_bsgs, s2_bsgs, avg_f, hit_fft, s2_fft);
    if (avg_f > 0.01 && avg_b > 0.01)
        std::printf("  %.2fx", avg_b / avg_f);
    if (s1_hit > 0)
        std::printf("  [%d s1]", s1_hit);
    std::printf("\n");
}

int main() {
    std::printf("=== Stage 2: BSGS vs FFT polynomial (GMP-ECM B1/B2) ===\n\n");

    for (int i = 0; i < NCASES; ++i) {
        const auto& tc = CASES[i];
        int ncurves = 20;
        switch (tc.N) {
            case 1: bench<1>(tc, ncurves); break;
            case 2: bench<2>(tc, ncurves); break;
            case 3: bench<3>(tc, ncurves); break;
            case 4: bench<4>(tc, ncurves); break;
        }
    }
    return 0;
}
